CREATE TABLE FROM_CONFIG(
   TRANSPORT_ID         VARCHAR2(10),
   TRANSPORT_PASSWORD   VARCHAR2(45),
   PARTY_ID             VARCHAR2(10) NOT NULL,
   PARTY_DESCRIPTION    VARCHAR2(200),
   ROUTING_ID           VARCHAR2(39),
   ROUTING_DESCRIPTION  VARCHAR2(200),
   SIGN_ID              VARCHAR2(4),
   SUBSTITUTE_PARTY_ID  VARCHAR2(10),
   CONSTRAINT FROM_CONFIG_PK1 PRIMARY KEY (PARTY_ID)
);

CREATE INDEX "FROM_CONFIG_INDEX1"
  ON FROM_CONFIG
  (SUBSTITUTE_PARTY_ID);

CREATE TABLE TURNKEY_TRANSPORT_CONFIG (
  TRANSPORT_ID VARCHAR2(10) NOT NULL,
  TRANSPORT_PASSWORD VARCHAR2(60) NOT NULL,
  CONSTRAINT TURNKEY_TRANSPORT_CONFIG_PK1 PRIMARY KEY (TRANSPORT_ID)
);


CREATE TABLE TURNKEY_USER_PROFILE(
  USER_ID VARCHAR2(10) NOT NULL,
  USER_PASSWORD VARCHAR2(100) NOT NULL,
  USER_ROLE VARCHAR2(2),
  CONSTRAINT TURNKEY_USER_PROFILE_PK1 PRIMARY KEY (USER_ID)
);

INSERT INTO TURNKEY_USER_PROFILE (USER_ID,USER_PASSWORD,USER_ROLE) VALUES
 ('ADMIN','ADMIN','0');

CREATE TABLE SCHEDULE_CONFIG(
   TASK                VARCHAR2(30) NOT NULL,
   ENABLE               VARCHAR2(1),
   SCHEDULE_TYPE        VARCHAR2(10),
   SCHEDULE_WEEK        VARCHAR2(15),
   SCHEDULE_TIME        VARCHAR2(50),
   SCHEDULE_PERIOD      VARCHAR2(10),
   SCHEDULE_RANGE       VARCHAR2(15),
    CONSTRAINT SCHEDULE_CONFIG_PK1 PRIMARY KEY (TASK)
);


CREATE TABLE SIGN_CONFIG (
  SIGN_ID VARCHAR2(4) NOT NULL,
  SIGN_TYPE VARCHAR2(10)  DEFAULT NULL,
  PFX_PATH VARCHAR2(100)  DEFAULT NULL,
  SIGN_PASSWORD VARCHAR2(60)  DEFAULT NULL,
  CONSTRAINT SIGN_CONFIG_PK1 PRIMARY KEY (SIGN_ID)
);


CREATE TABLE TASK_CONFIG(
   CATEGORY_TYPE        VARCHAR2(5) NOT NULL,
   PROCESS_TYPE         VARCHAR2(10) NOT NULL,
   TASK                 VARCHAR2(15) NOT NULL,
   SRC_PATH             VARCHAR2(200),
   TARGET_PATH          VARCHAR2(200),
   FILE_FORMAT          VARCHAR2(20),
   VERSION              VARCHAR2(5),
   ENCODING             VARCHAR2(15),
   TRANS_CHINESE_DATE   VARCHAR2(1),
   CONSTRAINT TASK_CONFIG_PK1 PRIMARY KEY (CATEGORY_TYPE, PROCESS_TYPE, TASK)
);


CREATE TABLE TO_CONFIG(
   PARTY_ID             VARCHAR2(10) NOT NULL,
   PARTY_DESCRIPTION    VARCHAR2(200),
   ROUTING_ID           VARCHAR2(39),
   ROUTING_DESCRIPTION  VARCHAR2(200),
   FROM_PARTY_ID        VARCHAR2(10),
   CONSTRAINT TO_CONFIG_PK1 PRIMARY KEY (FROM_PARTY_ID, PARTY_ID)
);


CREATE TABLE TURNKEY_MESSAGE_LOG (
  SEQNO VARCHAR2(8) NOT NULL,
  SUBSEQNO VARCHAR2(5) NOT NULL,
  UUID VARCHAR2(40) DEFAULT NULL,
  MESSAGE_TYPE VARCHAR2(10) DEFAULT NULL,
  CATEGORY_TYPE VARCHAR2(5) DEFAULT NULL,
  PROCESS_TYPE VARCHAR2(10) DEFAULT NULL,
  FROM_PARTY_ID VARCHAR2(10) DEFAULT NULL,
  TO_PARTY_ID VARCHAR2(10) DEFAULT NULL,
  MESSAGE_DTS VARCHAR2(17) DEFAULT NULL,
  CHARACTER_COUNT VARCHAR2(10) DEFAULT NULL,
  STATUS VARCHAR2(5) DEFAULT NULL,
  IN_OUT_BOUND VARCHAR2(1) DEFAULT NULL,
  FROM_ROUTING_ID VARCHAR2(39) DEFAULT NULL,
  TO_ROUTING_ID VARCHAR2(39) DEFAULT NULL,
  INVOICE_IDENTIFIER VARCHAR2(30) DEFAULT NULL,
  CONSTRAINT TURNKEY_MESSAGE_LOG_PK1 PRIMARY KEY (SEQNO, SUBSEQNO)
);

CREATE INDEX "TURNKEY_MESSAGE_LOG_INDEX1"
  ON TURNKEY_MESSAGE_LOG
  (MESSAGE_DTS);

CREATE INDEX "TURNKEY_MESSAGE_LOG_INDEX2"
  ON TURNKEY_MESSAGE_LOG
  (UUID);

CREATE TABLE TURNKEY_MESSAGE_LOG_DETAIL(
   SEQNO                VARCHAR2(8) NOT NULL,
   SUBSEQNO             VARCHAR2(5) NOT NULL,
   PROCESS_DTS          VARCHAR2(17),
   TASK                 VARCHAR2(30) NOT NULL,
   STATUS               VARCHAR2(5),
   FILENAME             VARCHAR2(300),
   UUID                 VARCHAR2(40),
   CONSTRAINT TURNKEY_MESSAGE_LOG_DETAIL_PK1 PRIMARY KEY (SEQNO, SUBSEQNO, TASK)
);

CREATE INDEX "TK_MESSAGE_LOG_DETAIL_INDEX1"
  ON TURNKEY_MESSAGE_LOG_DETAIL
  (FILENAME);

CREATE TABLE TURNKEY_SEQUENCE(
   SEQUENCE VARCHAR2(8) NOT NULL,
   CONSTRAINT TURNKEY_SEQUENCE_PK1 PRIMARY KEY (SEQUENCE)
);




CREATE TABLE TURNKEY_SYSEVENT_LOG(
   EVENTDTS             VARCHAR2(17) NOT NULL,
   PARTY_ID             VARCHAR2(10),
   SEQNO                VARCHAR2(8),
   SUBSEQNO             VARCHAR2(5),
   ERRORCODE            VARCHAR2(4),
   UUID                 VARCHAR2(40),
   INFORMATION1         VARCHAR2(100),
   INFORMATION2         VARCHAR2(100),
   INFORMATION3         VARCHAR2(100),
   MESSAGE1             VARCHAR2(100),
   MESSAGE2             VARCHAR2(100),
   MESSAGE3             VARCHAR2(100),
   MESSAGE4             VARCHAR2(100),
   MESSAGE5             VARCHAR2(100),
   MESSAGE6             VARCHAR2(100),
   CONSTRAINT TURNKEY_SYSEVENT_LOG_PK1 PRIMARY KEY (EVENTDTS)
);

CREATE INDEX "TURNKEY_SYSEVENT_LOG_INDEX1"
  ON TURNKEY_SYSEVENT_LOG
  (SEQNO, SUBSEQNO);

CREATE INDEX "TURNKEY_SYSEVENT_LOG_INDEX2"
  ON TURNKEY_SYSEVENT_LOG
  (UUID);
