/*
 Platform.js <https://mths.be/platform>
 Copyright 2014-2018 Benjamin Tan <https://bnjmnt4n.now.sh/>
 Copyright 2011-2013 John-David Dalton
 Available under MIT license <https://mths.be/mit>
*/
(function(){function c(a){a=String(a);return a.charAt(0).toUpperCase()+a.slice(1)}function h(a,f){var e=-1,b=a?a.length:0;if("number"==typeof b&&-1<b&&b<=C)for(;++e<b;)f(a[e],e,a);else g(a,f)}function b(a){a=String(a).replace(/^ +| +$/g,"");return/^(?:webOS|i(?:OS|P))/.test(a)?a:c(a)}function g(a,f){for(var e in a)A.call(a,e)&&f(a[e],e,a)}function l(a){return null==a?c(a):r.call(a).slice(8,-1)}function m(a,f){var e=null!=a?typeof a[f]:"number";return!/^(?:boolean|number|string|undefined)$/.test(e)&&
("object"==e?!!a[f]:!0)}function f(a){return String(a).replace(/([ -])(?!$)/g,"$1?")}function n(a,f){var e=null;h(a,function(b,d){e=f(e,b,d,a)});return e}function d(a){function c(e){return n(e,function(e,d){var c=d.pattern||f(d);!e&&(e=RegExp("\\b"+c+" *\\d+[.\\w_]*","i").exec(a)||RegExp("\\b"+c+" *\\w+-[\\w]*","i").exec(a)||RegExp("\\b"+c+"(?:; *(?:[a-z]+[_-])?[a-z]+\\d+|[^ ();-]*)","i").exec(a))&&((e=String(d.label&&!RegExp(c,"i").test(d.label)?d.label:e).split("/"))[1]&&!/[\d.]+/.test(e[0])&&(e[0]+=
" "+e[1]),d=d.label||d,e=b(e[0].replace(RegExp(c,"i"),d).replace(RegExp("; *(?:"+d+"[_-])?","i")," ").replace(RegExp("("+d+")[-_.]?(\\w)","i"),"$1 $2")));return e})}function w(f){return n(f,function(f,e){return f||(RegExp(e+"(?:-[\\d.]+/|(?: for [\\w-]+)?[ /-])([\\d.]+[^ ();/_-]*)","i").exec(a)||0)[1]||null})}var p=e,h=a&&"object"==typeof a&&"String"!=l(a);h&&(p=a,a=null);var q=p.navigator||{},t=q.userAgent||"";a||(a=t);var C=h?!!q.likeChrome:/\bChrome\b/.test(a)&&!/internal|\n/i.test(r.toString()),
x=h?"Object":"ScriptBridgingProxyObject",B=h?"Object":"Environment",A=h&&p.java?"JavaPackage":l(p.java),ba=h?"Object":"RuntimeObject";B=(A=/\bJava/.test(A)&&p.java)&&l(p.environment)==B;var Z=A?"a":"\u03b1",S=A?"b":"\u03b2",T=p.document||{},ca=p.operamini||p.opera,ea=y.test(ea=h&&ca?ca["[[Class]]"]:l(ca))?ea:ca=null,k,U=a;h=[];var fa=null,V=a==t;t=V&&ca&&"function"==typeof ca.version&&ca.version();var E=function(e){return n(e,function(e,d){return e||RegExp("\\b"+(d.pattern||f(d))+"\\b","i").exec(a)&&
(d.label||d)})}([{label:"EdgeHTML",pattern:"Edge"},"Trident",{label:"WebKit",pattern:"AppleWebKit"},"iCab","Presto","NetFront","Tasman","KHTML","Gecko"]),u=function(e){return n(e,function(e,d){return e||RegExp("\\b"+(d.pattern||f(d))+"\\b","i").exec(a)&&(d.label||d)})}(["Adobe AIR","Arora","Avant Browser","Breach","Camino","Electron","Epiphany","Fennec","Flock","Galeon","GreenBrowser","iCab","Iceweasel","K-Meleon","Konqueror","Lunascape","Maxthon",{label:"Microsoft Edge",pattern:"Edge"},"Midori",
"Nook Browser","PaleMoon","PhantomJS","Raven","Rekonq","RockMelt",{label:"Samsung Internet",pattern:"SamsungBrowser"},"SeaMonkey",{label:"Silk",pattern:"(?:Cloud9|Silk-Accelerated)"},"Sleipnir","SlimBrowser",{label:"SRWare Iron",pattern:"Iron"},"Sunrise","Swiftfox","Waterfox","WebPositive","Opera Mini",{label:"Opera Mini",pattern:"OPiOS"},"Opera",{label:"Opera",pattern:"OPR"},"Chrome",{label:"Chrome Mobile",pattern:"(?:CriOS|CrMo)"},{label:"Firefox",pattern:"(?:Firefox|Minefield)"},{label:"Firefox for iOS",
pattern:"FxiOS"},{label:"IE",pattern:"IEMobile"},{label:"IE",pattern:"MSIE"},"Safari"]),F=c([{label:"BlackBerry",pattern:"BB10"},"BlackBerry",{label:"Galaxy S",pattern:"GT-I9000"},{label:"Galaxy S2",pattern:"GT-I9100"},{label:"Galaxy S3",pattern:"GT-I9300"},{label:"Galaxy S4",pattern:"GT-I9500"},{label:"Galaxy S5",pattern:"SM-G900"},{label:"Galaxy S6",pattern:"SM-G920"},{label:"Galaxy S6 Edge",pattern:"SM-G925"},{label:"Galaxy S7",pattern:"SM-G930"},{label:"Galaxy S7 Edge",pattern:"SM-G935"},"Google TV",
"Lumia","iPad","iPod","iPhone","Kindle",{label:"Kindle Fire",pattern:"(?:Cloud9|Silk-Accelerated)"},"Nexus","Nook","PlayBook","PlayStation Vita","PlayStation","TouchPad","Transformer",{label:"Wii U",pattern:"WiiU"},"Wii","Xbox One",{label:"Xbox 360",pattern:"Xbox"},"Xoom"]),K=function(e){return n(e,function(e,d,b){return e||(d[F]||d[/^[a-z]+(?: +[a-z]+\b)*/i.exec(F)]||RegExp("\\b"+f(b)+"(?:\\b|\\w*\\d)","i").exec(a))&&b})}({Apple:{iPad:1,iPhone:1,iPod:1},Archos:{},Amazon:{Kindle:1,"Kindle Fire":1},
Asus:{Transformer:1},"Barnes & Noble":{Nook:1},BlackBerry:{PlayBook:1},Google:{"Google TV":1,Nexus:1},HP:{TouchPad:1},HTC:{},LG:{},Microsoft:{Xbox:1,"Xbox One":1},Motorola:{Xoom:1},Nintendo:{"Wii U":1,Wii:1},Nokia:{Lumia:1},Samsung:{"Galaxy S":1,"Galaxy S2":1,"Galaxy S3":1,"Galaxy S4":1},Sony:{PlayStation:1,"PlayStation Vita":1}}),v=function(e){return n(e,function(e,d){var c=d.pattern||f(d);if(!e&&(e=RegExp("\\b"+c+"(?:/[\\d.]+|[ \\w.]*)","i").exec(a))){var g=e,l=d.label||d,p={"10.0":"10","6.4":"10 Technical Preview",
"6.3":"8.1","6.2":"8","6.1":"Server 2008 R2 / 7","6.0":"Server 2008 / Vista","5.2":"Server 2003 / XP 64-bit","5.1":"XP","5.01":"2000 SP1","5.0":"2000","4.0":"NT","4.90":"ME"};c&&l&&/^Win/i.test(g)&&!/^Windows Phone /i.test(g)&&(p=p[/[\d.]+$/.exec(g)])&&(g="Windows "+p);g=String(g);c&&l&&(g=g.replace(RegExp(c,"i"),l));e=g=b(g.replace(/ ce$/i," CE").replace(/\bhpw/i,"web").replace(/\bMacintosh\b/,"Mac OS").replace(/_PowerPC\b/i," OS").replace(/\b(OS X) [^ \d]+/i,"$1").replace(/\bMac (OS X)\b/,"$1").replace(/\/(\d)/,
" $1").replace(/_/g,".").replace(/(?: BePC|[ .]*fc[ \d.]+)$/i,"").replace(/\bx86\.64\b/gi,"x86_64").replace(/\b(Windows Phone) OS\b/,"$1").replace(/\b(Chrome OS \w+) [\d.]+\b/,"$1").split(" on ")[0])}return e})}(["Windows Phone","Android","CentOS",{label:"Chrome OS",pattern:"CrOS"},"Debian","Fedora","FreeBSD","Gentoo","Haiku","Kubuntu","Linux Mint","OpenBSD","Red Hat","SuSE","Ubuntu","Xubuntu","Cygwin","Symbian OS","hpwOS","webOS ","webOS","Tablet OS","Tizen","Linux","Mac OS X","Macintosh","Mac",
"Windows 98;","Windows "]);E&&(E=[E]);K&&!F&&(F=c([K]));if(k=/\bGoogle TV\b/.exec(F))F=k[0];/\bSimulator\b/i.test(a)&&(F=(F?F+" ":"")+"Simulator");"Opera Mini"==u&&/\bOPiOS\b/.test(a)&&h.push("running in Turbo/Uncompressed mode");"IE"==u&&/\blike iPhone OS\b/.test(a)?(k=d(a.replace(/like iPhone OS/,"")),K=k.manufacturer,F=k.product):/^iP/.test(F)?(u||(u="Safari"),v="iOS"+((k=/ OS ([\d_]+)/i.exec(a))?" "+k[1].replace(/_/g,"."):"")):"Konqueror"!=u||/buntu/i.test(v)?K&&"Google"!=K&&(/Chrome/.test(u)&&
!/\bMobile Safari\b/i.test(a)||/\bVita\b/.test(F))||/\bAndroid\b/.test(v)&&/^Chrome/.test(u)&&/\bVersion\//i.test(a)?(u="Android Browser",v=/\bAndroid\b/.test(v)?v:"Android"):"Silk"==u?(/\bMobi/i.test(a)||(v="Android",h.unshift("desktop mode")),/Accelerated *= *true/i.test(a)&&h.unshift("accelerated")):"PaleMoon"==u&&(k=/\bFirefox\/([\d.]+)\b/.exec(a))?h.push("identifying as Firefox "+k[1]):"Firefox"==u&&(k=/\b(Mobile|Tablet|TV)\b/i.exec(a))?(v||(v="Firefox OS"),F||(F=k[1])):!u||(k=!/\bMinefield\b/i.test(a)&&
/\b(?:Firefox|Safari)\b/.exec(u))?(u&&!F&&/[\/,]|^[^(]+?\)/.test(a.slice(a.indexOf(k+"/")+8))&&(u=null),(k=F||K||v)&&(F||K||/\b(?:Android|Symbian OS|Tablet OS|webOS)\b/.test(v))&&(u=/[a-z]+(?: Hat)?/i.exec(/\bAndroid\b/.test(v)?v:k)+" Browser")):"Electron"==u&&(k=(/\bChrome\/([\d.]+)\b/.exec(a)||0)[1])&&h.push("Chromium "+k):v="Kubuntu";t||(t=w(["(?:Cloud9|CriOS|CrMo|Edge|FxiOS|IEMobile|Iron|Opera ?Mini|OPiOS|OPR|Raven|SamsungBrowser|Silk(?!/[\\d.]+$))","Version",f(u),"(?:Firefox|Minefield|NetFront)"]));
if(k="iCab"==E&&3<parseFloat(t)&&"WebKit"||/\bOpera\b/.test(u)&&(/\bOPR\b/.test(a)?"Blink":"Presto")||/\b(?:Midori|Nook|Safari)\b/i.test(a)&&!/^(?:Trident|EdgeHTML)$/.test(E)&&"WebKit"||!E&&/\bMSIE\b/i.test(a)&&("Mac OS"==v?"Tasman":"Trident")||"WebKit"==E&&/\bPlayStation\b(?! Vita\b)/i.test(u)&&"NetFront")E=[k];"IE"==u&&(k=(/; *(?:XBLWP|ZuneWP)(\d+)/i.exec(a)||0)[1])?(u+=" Mobile",v="Windows Phone "+(/\+$/.test(k)?k:k+".x"),h.unshift("desktop mode")):/\bWPDesktop\b/i.test(a)?(u="IE Mobile",v="Windows Phone 8.x",
h.unshift("desktop mode"),t||(t=(/\brv:([\d.]+)/.exec(a)||0)[1])):"IE"!=u&&"Trident"==E&&(k=/\brv:([\d.]+)/.exec(a))&&(u&&h.push("identifying as "+u+(t?" "+t:"")),u="IE",t=k[1]);if(V){if(m(p,"global"))if(A&&(k=A.lang.System,U=k.getProperty("os.arch"),v=v||k.getProperty("os.name")+" "+k.getProperty("os.version")),B){try{t=p.require("ringo/engine").version.join("."),u="RingoJS"}catch(Q){(k=p.system)&&k.global.system==p.system&&(u="Narwhal",v||(v=k[0].os||null))}u||(u="Rhino")}else"object"==typeof p.process&&
!p.process.browser&&(k=p.process)&&("object"==typeof k.versions&&("string"==typeof k.versions.electron?(h.push("Node "+k.versions.node),u="Electron",t=k.versions.electron):"string"==typeof k.versions.nw&&(h.push("Chromium "+t,"Node "+k.versions.node),u="NW.js",t=k.versions.nw)),u||(u="Node.js",U=k.arch,v=k.platform,t=(t=/[\d.]+/.exec(k.version))?t[0]:null));else l(k=p.runtime)==x?(u="Adobe AIR",v=k.flash.system.Capabilities.os):l(k=p.phantom)==ba?(u="PhantomJS",t=(k=k.version||null)&&k.major+"."+
k.minor+"."+k.patch):"number"==typeof T.documentMode&&(k=/\bTrident\/(\d+)/i.exec(a))?(t=[t,T.documentMode],(k=+k[1]+4)!=t[1]&&(h.push("IE "+t[1]+" mode"),E&&(E[1]=""),t[1]=k),t="IE"==u?String(t[1].toFixed(1)):t[0]):"number"==typeof T.documentMode&&/^(?:Chrome|Firefox)\b/.test(u)&&(h.push("masking as "+u+" "+t),u="IE",t="11.0",E=["Trident"],v="Windows");v=v&&b(v)}t&&(k=/(?:[ab]|dp|pre|[ab]\d+pre)(?:\d+\+?)?$/i.exec(t)||/(?:alpha|beta)(?: ?\d)?/i.exec(a+";"+(V&&q.appMinorVersion))||/\bMinefield\b/i.test(a)&&
"a")&&(fa=/b/i.test(k)?"beta":"alpha",t=t.replace(RegExp(k+"\\+?$"),"")+("beta"==fa?S:Z)+(/\d+\+?/.exec(k)||""));if("Fennec"==u||"Firefox"==u&&/\b(?:Android|Firefox OS)\b/.test(v))u="Firefox Mobile";else if("Maxthon"==u&&t)t=t.replace(/\.[\d.]+/,".x");else if(/\bXbox\b/i.test(F))"Xbox 360"==F&&(v=null),"Xbox 360"==F&&/\bIEMobile\b/.test(a)&&h.unshift("mobile mode");else if(!/^(?:Chrome|IE|Opera)$/.test(u)&&(!u||F||/Browser|Mobi/.test(u))||"Windows CE"!=v&&!/Mobi/i.test(a))if("IE"==u&&V)try{null===
p.external&&h.unshift("platform preview")}catch(Q){h.unshift("embedded")}else(/\bBlackBerry\b/.test(F)||/\bBB10\b/.test(a))&&(k=(RegExp(F.replace(/ +/g," *")+"/([.\\d]+)","i").exec(a)||0)[1]||t)?(k=[k,/BB10/.test(a)],v=(k[1]?(F=null,K="BlackBerry"):"Device Software")+" "+k[0],t=null):this!=g&&"Wii"!=F&&(V&&ca||/Opera/.test(u)&&/\b(?:MSIE|Firefox)\b/i.test(a)||"Firefox"==u&&/\bOS X (?:\d+\.){2,}/.test(v)||"IE"==u&&(v&&!/^Win/.test(v)&&5.5<t||/\bWindows XP\b/.test(v)&&8<t||8==t&&!/\bTrident\b/.test(a)))&&
!y.test(k=d.call(g,a.replace(y,"")+";"))&&k.name&&(k="ing as "+k.name+((k=k.version)?" "+k:""),y.test(u)?(/\bIE\b/.test(k)&&"Mac OS"==v&&(v=null),k="identify"+k):(k="mask"+k,u=ea?b(ea.replace(/([a-z])([A-Z])/g,"$1 $2")):"Opera",/\bIE\b/.test(k)&&(v=null),V||(t=null)),E=["Presto"],h.push(k));else u+=" Mobile";if(k=(/\bAppleWebKit\/([\d.]+\+?)/i.exec(a)||0)[1]){k=[parseFloat(k.replace(/\.(\d)$/,".0$1")),k];if("Safari"==u&&"+"==k[1].slice(-1))u="WebKit Nightly",fa="alpha",t=k[1].slice(0,-1);else if(t==
k[1]||t==(k[2]=(/\bSafari\/([\d.]+\+?)/i.exec(a)||0)[1]))t=null;k[1]=(/\bChrome\/([\d.]+)/i.exec(a)||0)[1];537.36==k[0]&&537.36==k[2]&&28<=parseFloat(k[1])&&"WebKit"==E&&(E=["Blink"]);V&&(C||k[1])?(E&&(E[1]="like Chrome"),k=k[1]||(k=k[0],530>k?1:532>k?2:532.05>k?3:533>k?4:534.03>k?5:534.07>k?6:534.1>k?7:534.13>k?8:534.16>k?9:534.24>k?10:534.3>k?11:535.01>k?12:535.02>k?"13+":535.07>k?15:535.11>k?16:535.19>k?17:536.05>k?18:536.1>k?19:537.01>k?20:537.11>k?"21+":537.13>k?23:537.18>k?24:537.24>k?25:537.36>
k?26:"Blink"!=E?"27":"28")):(E&&(E[1]="like Safari"),k=(k=k[0],400>k?1:500>k?2:526>k?3:533>k?4:534>k?"4+":535>k?5:537>k?6:538>k?7:601>k?8:"8"));E&&(E[1]+=" "+(k+="number"==typeof k?".x":/[.+]/.test(k)?"":"+"));"Safari"==u&&(!t||45<parseInt(t))&&(t=k)}"Opera"==u&&(k=/\bzbov|zvav$/.exec(v))?(u+=" ",h.unshift("desktop mode"),"zvav"==k?(u+="Mini",t=null):u+="Mobile",v=v.replace(RegExp(" *"+k+"$"),"")):"Safari"==u&&/\bChrome\b/.exec(E&&E[1])&&(h.unshift("desktop mode"),u="Chrome Mobile",t=null,/\bOS X\b/.test(v)?
(K="Apple",v="iOS 4.3+"):v=null);t&&0==t.indexOf(k=/[\d.]+$/.exec(v))&&-1<a.indexOf("/"+k+"-")&&(v=String(v.replace(k,"")).replace(/^ +| +$/g,""));E&&!/\b(?:Avant|Nook)\b/.test(u)&&(/Browser|Lunascape|Maxthon/.test(u)||"Safari"!=u&&/^iOS/.test(v)&&/\bSafari\b/.test(E[1])||/^(?:Adobe|Arora|Breach|Midori|Opera|Phantom|Rekonq|Rock|Samsung Internet|Sleipnir|Web)/.test(u)&&E[1])&&(k=E[E.length-1])&&h.push(k);h.length&&(h=["("+h.join("; ")+")"]);K&&F&&0>F.indexOf(K)&&h.push("on "+K);F&&h.push((/^on /.test(h[h.length-
1])?"":"on ")+F);if(v){var ia=(k=/ ([\d.+]+)$/.exec(v))&&"/"==v.charAt(v.length-k[0].length-1);v={architecture:32,family:k&&!ia?v.replace(k[0],""):v,version:k?k[1]:null,toString:function(){var a=this.version;return this.family+(a&&!ia?" "+a:"")+(64==this.architecture?" 64-bit":"")}}}(k=/\b(?:AMD|IA|Win|WOW|x86_|x)64\b/i.exec(U))&&!/\bi686\b/i.test(U)?(v&&(v.architecture=64,v.family=v.family.replace(RegExp(" *"+k),"")),u&&(/\bWOW64\b/i.test(a)||V&&/\w(?:86|32)$/.test(q.cpuClass||q.platform)&&!/\bWin64; x64\b/i.test(a))&&
h.unshift("32-bit")):v&&/^OS X/.test(v.family)&&"Chrome"==u&&39<=parseFloat(t)&&(v.architecture=64);a||(a=null);p={};p.description=a;p.layout=E&&E[0];p.manufacturer=K;p.name=u;p.prerelease=fa;p.product=F;p.ua=a;p.version=u&&t;p.os=v||{architecture:null,family:null,version:null,toString:function(){return"null"}};p.parse=d;p.toString=function(){return this.description||""};p.version&&h.unshift(t);p.name&&h.unshift(u);v&&u&&(v!=String(v).split(" ")[0]||v!=u.split(" ")[0]&&!F)&&h.push(F?"("+v+")":"on "+
v);h.length&&(p.description=h.join(" "));return p}var a={"function":!0,object:!0},e=a[typeof window]&&window||this,p=a[typeof exports]&&exports;a=a[typeof module]&&module&&!module.nodeType&&module;var w=p&&a&&"object"==typeof global&&global;!w||w.global!==w&&w.window!==w&&w.self!==w||(e=w);var C=Math.pow(2,53)-1,y=/\bOpera/;w=Object.prototype;var A=w.hasOwnProperty,r=w.toString,x=d();"function"==typeof define&&"object"==typeof define.amd&&define.amd?(e.platform=x,define(function(){return x})):p&&
a?g(x,function(a,e){p[e]=a}):e.platform=x}).call(this);
function buildIOSMeta(){for(var c=[{name:"viewport",content:"width=device-width, height=device-height, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no"},{name:"apple-mobile-web-app-capable",content:"yes"},{name:"apple-mobile-web-app-status-bar-style",content:"black"}],h=0;h<c.length;h++){var b=document.createElement("meta");b.name=c[h].name;b.content=c[h].content;var g=window.document.head.querySelector('meta[name="'+b.name+'"]');g&&g.parentNode.removeChild(g);window.document.head.appendChild(b)}}
function hideIOSFullscreenPanel(){jQuery(".xxx-ios-fullscreen-message").css("display","none");jQuery(".xxx-ios-fullscreen-scroll").css("display","none");jQuery(".xxx-game-iframe-full").removeClass("xxx-game-iframe-iphone-se")}function buildIOSFullscreenPanel(){jQuery("body").append('<div class="xxx-ios-fullscreen-message"><div class="xxx-ios-fullscreen-swipe"></div></div><div class="xxx-ios-fullscreen-scroll"></div>')}
function showIOSFullscreenPanel(){jQuery(".xxx-ios-fullscreen-message").css("display","block");jQuery(".xxx-ios-fullscreen-scroll").css("display","block")}
function __iosResize(){window.scrollTo(0,0);if("iPhone"===platform.product)switch(window.devicePixelRatio){case 2:switch(window.innerWidth){case 568:320!==window.innerHeight&&jQuery(".xxx-game-iframe-full").addClass("xxx-game-iframe-iphone-se");break;case 667:375===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;default:hideIOSFullscreenPanel()}break;case 3:switch(window.innerWidth){case 736:414===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;
case 724:375===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;default:hideIOSFullscreenPanel()}break;default:hideIOSFullscreenPanel()}}function iosResize(){__iosResize();setTimeout(function(){__iosResize()},500)}$(document).ready(function(){platform&&"iPhone"===platform.product&&"Safari"===platform.name&&(buildIOSFullscreenPanel(),buildIOSMeta())});jQuery(window).resize(function(){platform&&"iPhone"===platform.product&&"Safari"===platform.name&&iosResize()});
(function(){var c="undefined"!==typeof window&&"undefined"!==typeof window.document?window.document:{},h="undefined"!==typeof module&&module.exports,b="undefined"!==typeof Element&&"ALLOW_KEYBOARD_INPUT"in Element,g=function(){for(var f,b=["requestFullscreen exitFullscreen fullscreenElement fullscreenEnabled fullscreenchange fullscreenerror".split(" "),"webkitRequestFullscreen webkitExitFullscreen webkitFullscreenElement webkitFullscreenEnabled webkitfullscreenchange webkitfullscreenerror".split(" "),
"webkitRequestFullScreen webkitCancelFullScreen webkitCurrentFullScreenElement webkitCancelFullScreen webkitfullscreenchange webkitfullscreenerror".split(" "),"mozRequestFullScreen mozCancelFullScreen mozFullScreenElement mozFullScreenEnabled mozfullscreenchange mozfullscreenerror".split(" "),"msRequestFullscreen msExitFullscreen msFullscreenElement msFullscreenEnabled MSFullscreenChange MSFullscreenError".split(" ")],d=0,a=b.length,e={};d<a;d++)if((f=b[d])&&f[1]in c){for(d=0;d<f.length;d++)e[b[0][d]]=
f[d];return e}return!1}(),l={change:g.fullscreenchange,error:g.fullscreenerror},m={request:function(f){var l=g.requestFullscreen;f=f||c.documentElement;if(/5\.1[.\d]* Safari/.test(navigator.userAgent))f[l]();else f[l](b&&Element.ALLOW_KEYBOARD_INPUT)},exit:function(){c[g.exitFullscreen]()},toggle:function(f){this.isFullscreen?this.exit():this.request(f)},onchange:function(f){this.on("change",f)},onerror:function(f){this.on("error",f)},on:function(f,b){var d=l[f];d&&c.addEventListener(d,b,!1)},off:function(f,
b){var d=l[f];d&&c.removeEventListener(d,b,!1)},raw:g};g?(Object.defineProperties(m,{isFullscreen:{get:function(){return!!c[g.fullscreenElement]}},element:{enumerable:!0,get:function(){return c[g.fullscreenElement]}},enabled:{enumerable:!0,get:function(){return!!c[g.fullscreenEnabled]}}}),h?module.exports=m:window.screenfull=m):h?module.exports=!1:window.screenfull=!1})();var s_iScaleFactor=1,s_oCanvasLeft,s_oCanvasTop;
(function(c){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(c)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(c.substr(0,
4))})(navigator.userAgent||navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(c){console.log(c)}function isChrome(){return/Chrome/.test(navigator.userAgent)&&/Google Inc/.test(navigator.vendor)}function isIOS(){var c="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");for(-1!==navigator.userAgent.toLowerCase().indexOf("iphone")&&(s_bIsIphone=!0);c.length;)if(navigator.platform===c.pop())return!0;return s_bIsIphone=!1}
function getSize(c){var h=c.toLowerCase(),b=window.document,g=b.documentElement;if(void 0===window["inner"+c])c=g["client"+c];else if(window["inner"+c]!=g["client"+c]){var l=b.createElement("body");l.id="vpw-test-b";l.style.cssText="overflow:scroll";var m=b.createElement("div");m.id="vpw-test-d";m.style.cssText="position:absolute;top:-1000px";m.innerHTML="<style>@media("+h+":"+g["client"+c]+"px){body#vpw-test-b div#vpw-test-d{"+h+":7px!important}}</style>";l.appendChild(m);g.insertBefore(l,b.head);
c=7==m["offset"+c]?g["client"+c]:window["inner"+c];g.removeChild(l)}else c=window["inner"+c];return c}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var c=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<c?c:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var c=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var h=getSize("Width");_checkOrientation(h,c);var b=Math.min(c/CANVAS_HEIGHT,h/CANVAS_WIDTH),g=CANVAS_WIDTH*b;b*=CANVAS_HEIGHT;if(b<c){var l=c-b;b+=l;g+=CANVAS_WIDTH/CANVAS_HEIGHT*l}else g<h&&(l=h-g,g+=l,b+=CANVAS_HEIGHT/CANVAS_WIDTH*l);l=c/2-b/2;var m=h/2-g/2,f=CANVAS_WIDTH/g;if(m*f<-EDGEBOARD_X||l*f<-EDGEBOARD_Y)b=Math.min(c/(CANVAS_HEIGHT-2*
EDGEBOARD_Y),h/(CANVAS_WIDTH-2*EDGEBOARD_X)),g=CANVAS_WIDTH*b,b*=CANVAS_HEIGHT,l=(c-b)/2,m=(h-g)/2,f=CANVAS_WIDTH/g;s_iOffsetX=-1*m*f;s_iOffsetY=-1*l*f;0<=l&&(s_iOffsetY=0);0<=m&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oLevelMenu&&s_oLevelMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);s_bIsIphone?(canvas=document.getElementById("canvas"),s_oStage.canvas.width=2*g,s_oStage.canvas.height=
2*b,canvas.style.width=g+"px",canvas.style.height=b+"px",s_oStage.scaleX=s_oStage.scaleY=2*Math.min(g/CANVAS_WIDTH,b/CANVAS_HEIGHT)):s_bMobile||isChrome()?($("#canvas").css("width",g+"px"),$("#canvas").css("height",b+"px")):(s_oStage.canvas.width=g,s_oStage.canvas.height=b,s_iScaleFactor=Math.min(g/CANVAS_WIDTH,b/CANVAS_HEIGHT),s_oStage.scaleX=s_oStage.scaleY=s_iScaleFactor);0>l||(l=(c-b)/2);$("#canvas").css("top",l+"px");$("#canvas").css("left",m+"px");fullscreenHandler()}}
function createBitmap(c,h,b){var g=new createjs.Bitmap(c),l=new createjs.Shape;h&&b?l.graphics.beginFill("#fff").drawRect(0,0,h,b):l.graphics.beginFill("#ff0").drawRect(0,0,c.width,c.height);g.hitArea=l;return g}
function _checkOrientation(c,h){s_bMobile&&ENABLE_CHECK_ORIENTATION&&(c>h?"landscape"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),s_oMain.stopUpdate()):"portrait"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),
s_oMain.stopUpdate()))}function createSprite(c,h,b,g,l,m){c=null!==h?new createjs.Sprite(c,h):new createjs.Sprite(c);h=new createjs.Shape;h.graphics.beginFill("#000000").drawRect(-b,-g,l,m);c.hitArea=h;return c}function randomFloatBetween(c,h,b){"undefined"===typeof b&&(b=2);return parseFloat(Math.min(c+Math.random()*(h-c),h).toFixed(b))}function formatTime(c){c/=1E3;var h=Math.floor(c/60);c=Math.floor(c-60*h);var b="";b=10>h?b+("0"+h+":"):b+(h+":");return 10>c?b+("0"+c):b+c}
function NoClickDelay(c){this.element=c;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(c){for(var h=c.length,b,g;0<h;)g=Math.floor(Math.random()*h),h--,b=c[h],c[h]=c[g],c[g]=b;return c}
NoClickDelay.prototype={handleEvent:function(c){switch(c.type){case "touchstart":this.onTouchStart(c);break;case "touchmove":this.onTouchMove(c);break;case "touchend":this.onTouchEnd(c)}},onTouchStart:function(c){c.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(c){this.moved=!0},onTouchEnd:function(c){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){c=document.elementFromPoint(c.changedTouches[0].clientX,c.changedTouches[0].clientY);3==c.nodeType&&(c=c.parentNode);var h=document.createEvent("MouseEvents");h.initEvent("click",!0,!0);c.dispatchEvent(h)}}};function toRadian(c){return Math.PI/180*c}function toDegree(c){return 180/Math.PI*c}function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(c){for(var h=window.location.search.substring(1).split("&"),b=0;b<h.length;b++){var g=h[b].split("=");if(g[0]==c)return g[1]}}function playSound(c,h,b){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(s_aSounds[c].play(),s_aSounds[c].volume(h),s_aSounds[c].loop(b),s_aSounds[c]):null}function stopSound(c){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[c].stop()}function setVolume(c,h){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[c].volume(h)}
function setMute(c,h){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[c].mute(h)}
(function(){function c(b){var c={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};b=b||window.event;b.type in c?document.body.className=c[b.type]:(document.body.className=this[h]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var h="hidden";h in document?document.addEventListener("visibilitychange",c):(h="mozHidden")in document?document.addEventListener("mozvisibilitychange",c):(h="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",c):(h="msHidden")in document?document.addEventListener("msvisibilitychange",c):"onfocusin"in document?document.onfocusin=document.onfocusout=c:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=c})();
function fullscreenHandler(){ENABLE_FULLSCREEN&&screenfull.enabled&&(s_bFullscreen=screen.height<window.innerHeight+3&&screen.height>window.innerHeight-3?!0:!1,null!==s_oInterface&&s_oInterface.resetFullscreenBut(),null!==s_oMenu&&s_oMenu.resetFullscreenBut())}if(screenfull.enabled)screenfull.on("change",function(){s_bFullscreen=screenfull.isFullscreen;null!==s_oInterface&&s_oInterface.resetFullscreenBut();null!==s_oMenu&&s_oMenu.resetFullscreenBut()});
function saveItem(c,h){s_bStorageAvailable&&localStorage.setItem(c,h)}function getItem(c){return s_bStorageAvailable?localStorage.getItem(c):null}
function CSpriteLibrary(){var c,h,b,g,l,m;this.init=function(f,n,d){b=h=0;g=f;l=n;m=d;c={}};this.addSprite=function(f,b){c.hasOwnProperty(f)||(c[f]={szPath:b,oSprite:new Image},h++)};this.getSprite=function(f){return c.hasOwnProperty(f)?c[f].oSprite:null};this._onSpritesLoaded=function(){l.call(m)};this._onSpriteLoaded=function(){g.call(m);++b===h&&this._onSpritesLoaded()};this.loadSprites=function(){for(var f in c)c[f].oSprite.oSpriteLibrary=this,c[f].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
c[f].oSprite.src=c[f].szPath};this.getNumSprites=function(){return h}}
var GAME_NAME="brick_out",CANVAS_WIDTH=840,CANVAS_HEIGHT=1024,EDGEBOARD_X=100,EDGEBOARD_Y=30,FPS_TIME=1E3/30,DISABLE_SOUND_MOBILE=!1,PRIMARY_FONT="domdiagonal_btregular",STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,ON_BUT_YES_DOWN=6,MAX_BONUS_BOUNCE=5,TYPES_OF_BRICK=6,TYPES_OF_BONUS=10,MAX_BRICK_FOR_ROW=7,MAX_BALL_SPAWN=4,MAX_VELOCITY_LIMIT=1.5,MIN_VELOCITY_LIMIT=.5,MAX_TIME_SHOT_BONUS=100,BONUS_MULTI_BALL=
0,TIME_BOUNCE_BALL=.01,BRICKS_LEVEL_POSITION,COLOR_TEXT_LEVEL,HEIGHT_OF_PADDLE=CANVAS_HEIGHT/2+370,OFFSET_BALL_PAD_Y=15,BONUS_OCCURRENCE_PER_LEVEL,PADDLE_DIMENSION=[80,150,210],SPACE_BETWEEN_BRICKS=-3,TIME_REFLECT_IRON_BRICK=100,LAUNCH_BALL_POS=.1,EDGE_OFFSET=102,OFFSET_BRICK_Y_POS=-16,OFFSET_HEIGHT_BRICK=0,OFFSET_WIDTH_BRICK=0,OFFSET_X_BRICK=-1,OFFSET_Y_BRICK=0,OFFSET_RADIUS_BALL=0,OFFSET_DIAGRAM_CHECK=25,OFFSETEDGEDOWN=83,OFFSETEDGEUP=50,OFFSETEDGERIGHT=106,OFFSETEDGELEFT=106,OFFSETPOWERUPFLOOR=
20,OFFSET_PAD_Y=15,OFFSET_PAD_MAGNETIC_Y=-1,OFFSET_CENTER_X_DIAGRAM=-35,OFFSET_CENTER_Y_DIAGRAM=-55,OFFSET_BRICK_SECTION_X=70,OFFSET_BRICK_SECTION_Y=15,OFFSET_DETECTION_BRICK_SECTION_X=-50,OFFSET_DETECTION_BRICK_SECTION_Y=60,OFFSET_DIM_X_CANNONS=32,OFFSET_CANNONS_Y_POS=14,REG_X_OFFSET_PADDLE_MAGNETIC=0,REG_Y_OFFSET_PADDLE_MAGNETIC=460,SPAWN_BONUS_PROBABILITY;BRICKS_LEVEL_POSITION=[];SPAWN_BONUS_PROBABILITY=[];COLOR_TEXT_LEVEL=[];
BRICKS_LEVEL_POSITION[0]=[3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0];BRICKS_LEVEL_POSITION[1]=[1,1,-1,4,-1,1,1,1,1,-1,4,-1,1,1,1,1,-1,4,-1,1,1,1,1,-1,4,-1,1,1,1,1,-1,4,-1,1,1,1,1,-1,4,-1,1,1,1,1,-1,4,-1,1,1,1,1,-1,4,-1,1,1,1,1,-1,4,-1,1,1];
BRICKS_LEVEL_POSITION[2]=[1,1,1,1,1,-1,-1,0,0,0,0,-1,-1,-1,3,3,3,-1,-1,-1,-1,2,2,-1,-1,-1,-1,-1,1,-1,-1,-1,-1,-1,-1,0,0,-1,-1,-1,-1,-1,3,3,3,-1,-1,-1,-1,2,2,2,2,-1,-1,-1,1,1,1,1,1,-1,-1,5,5,5,5,5,5,-1];BRICKS_LEVEL_POSITION[3]=[4,-1,-1,3,-1,-1,4,-1,-1,2,2,2,-1,-1,-1,1,1,1,1,1,-1,0,0,0,0,0,0,0,5,5,5,5,5,5,5,0,0,0,0,0,0,0,-1,1,1,1,1,1,1,-1,-1,2,2,2,-1,-1,4,-1,-1,3,-1,-1,4];
BRICKS_LEVEL_POSITION[4]=[4,4,-1,-1,-1,4,4,4,-1,-1,3,-1,-1,4,-1,-1,3,3,3,-1,-1,-1,3,3,3,3,3,-1,3,3,3,3,3,3,3,-1,5,5,5,5,5,-1,-1,5,5,5,5,5,-1,-1,5,2,5,2,5,-1,-1,5,5,5,5,5,-1,-1,5,5,1,5,5,-1,-1,5,5,1,5,5,-1,-1,0,0,0,0,0,-1];BRICKS_LEVEL_POSITION[5]=[1,-1,-1,3,-1,-1,1,1,-1,3,3,3,-1,1,1,3,3,3,3,3,1,1,-1,3,3,3,-1,1,1,1,0,0,0,1,1,-1,-1,-1,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,3,-1,-1,-1,3,-1,-1,1,1,-1,1,1,-1,-1,2,2,2,2,2,-1,-1,4,4,4,4,4,-1];
BRICKS_LEVEL_POSITION[6]=[5,5,5,5,5,5,5,3,-1,-1,5,-1,-1,3,1,-1,-1,5,-1,-1,1,0,-1,-1,5,-1,-1,0,2,-1,-1,5,-1,-1,2,2,-1,-1,5,-1,-1,2,0,-1,-1,5,-1,-1,0,1,-1,-1,5,-1,-1,1,3,-1,-1,5,-1,-1,3,5,5,5,5,5,5,5,0,1,3,2,3,1,0,1,1,3,2,3,2,2,3,3,3,2,3,3,3];BRICKS_LEVEL_POSITION[7]=[3,3,3,-1,3,3,3,3,4,3,-1,3,4,3,3,3,3,-1,3,3,3,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,0,-1,-1,-1,-1,-1,0,0,0,-1,-1,-1,0,0,0,0,0,-1,-1,0,0,0,0,0,-1,-1,-1,0,0,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1,-1,-1,-1,1,-1,1,-1,-1,-1,1,-1,-1,-1,1,1,1,-1,-1];
BRICKS_LEVEL_POSITION[8]=[5,5,5,-1,5,5,5,5,2,5,-1,5,0,5,5,5,5,-1,5,5,5,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,4,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,5,5,5,-1,5,5,5,5,1,5,-1,5,3,5,5,5,5,-1,5,5,5,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,4,-1,4,-1,4,-1,4];BRICKS_LEVEL_POSITION[9]=[1,1,1,1,2,2,2,1,1,1,2,2,2,2,1,1,1,1,2,2,2,1,1,1,2,2,2,2,1,1,4,5,4,2,2,1,1,4,-1,4,2,2,3,3,4,-1,4,0,0,3,4,4,-1,4,4,0,3,4,4,-1,4,4,0,3,4,4,-1,4,4,0,4,4,4,-1,4,4,4,4,4,4,-1,4,4,4,4,4,4,-1,4,4,4];
BONUS_OCCURRENCE_PER_LEVEL=[[20,15,5,15,1,5,10,15,14,14],[15,3,10,15,2,10,15,20,15,7],[20,1,5,25,2,7,1,20,23,9],[20,1,10,20,4,5,1,20,23,10],[10,1,15,20,6,10,2,20,20,5],[5,1,15,20,6,10,5,15,27,10],[10,2,10,25,2,10,5,15,25,10],[18,3,15,10,2,5,4,10,20,25,9],[10,1,15,20,6,10,2,20,20,5],[23,1,10,7,1,2,7,20,20,23]];SPAWN_BONUS_PROBABILITY[0]=15;SPAWN_BONUS_PROBABILITY[1]=15;SPAWN_BONUS_PROBABILITY[2]=15;SPAWN_BONUS_PROBABILITY[3]=15;SPAWN_BONUS_PROBABILITY[4]=15;SPAWN_BONUS_PROBABILITY[5]=15;
SPAWN_BONUS_PROBABILITY[6]=15;SPAWN_BONUS_PROBABILITY[7]=15;SPAWN_BONUS_PROBABILITY[8]=10;SPAWN_BONUS_PROBABILITY[9]=10;COLOR_TEXT_LEVEL[0]="#00CA1B";COLOR_TEXT_LEVEL[1]="#EBD100";COLOR_TEXT_LEVEL[2]="#FF0013";COLOR_TEXT_LEVEL[3]="#00A1E0";var ENABLE_FULLSCREEN,ENABLE_CHECK_ORIENTATION;TEXT_SCORE="SCORE";TEXT_SCORE_GAMEOVER="Total Score";TEXT_LEVEL="Level";TEXT_LEVEL_UPPERCASE="LEVEL";TEXT_COMPLETE="Complete";TEXT_CONGRATULATIONS="All levels completed... Congratulations!";TEXT_HELP_PAGE_1_PC="Move the paddle with your mouse to bounce the ball and destroy all the bricks! Grab any falling power-ups to get more points!";
TEXT_HELP_PAGE_1_MOBILE="Swipe the paddle to bounce the ball and destroy all the bricks! Grab any falling power-ups to get more points!";TEXT_DEVELOPED="DEVELOPED BY";var TEXT_CONFIRM_CLEAR_SAVINGS="ALL YOUR SAVINGS WILL BE DELETED.ARE YOU SURE?",TEXT_ARE_SURE="ARE YOU SURE?",TEXT_PRELOADER_CONTINUE="START",TEXT_ERR_LS="YOUR WEB BROWSER DOES NOT SUPPORT STORING SETTING LOCALLY. IN SAFARI, THE MOST COMMON CAUSE OF THIS IS USING 'PRIVATE BROWSING MODE'. SOME INFO MAY NOT SAVE OR SOME FEATURE MAY NOT WORK PROPERLY.";
TEXT_SHARE_IMAGE="200x200.jpg";TEXT_SHARE_TITLE="Congratulations!";TEXT_SHARE_MSG1="You collected <strong>";TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!";TEXT_SHARE_SHARE1="My score is ";TEXT_SHARE_SHARE2=" points! Can you do better";
function CPreloader(){var c,h,b,g,l,m,f,n,d,a;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.addSprite("200x200","./sprites/200x200.jpg");s_oSpriteLibrary.addSprite("but_start","./sprites/but_start.png");s_oSpriteLibrary.loadSprites();a=new createjs.Container;s_oStage.addChild(a)};this.unload=function(){a.removeAllChildren();d.unload()};this._onImagesLoaded=function(){};
this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var e=new createjs.Shape;e.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);a.addChild(e);e=s_oSpriteLibrary.getSprite("200x200");f=createBitmap(e);f.regX=.5*e.width;f.regY=.5*e.height;f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT/2-180;a.addChild(f);n=new createjs.Shape;n.graphics.beginFill("rgba(0,0,0,0.01)").drawRoundRect(f.x-100,f.y-100,200,200,10);a.addChild(n);f.mask=n;
e=s_oSpriteLibrary.getSprite("progress_bar");g=createBitmap(e);g.x=CANVAS_WIDTH/2-e.width/2;g.y=CANVAS_HEIGHT/2+50;a.addChild(g);c=e.width;h=e.height;l=new createjs.Shape;l.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(g.x,g.y,1,h);a.addChild(l);g.mask=l;b=new createjs.Text("","30px "+PRIMARY_FONT,"#fff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT/2+100;b.textBaseline="alphabetic";b.textAlign="center";a.addChild(b);e=s_oSpriteLibrary.getSprite("but_start");d=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/
2,e,TEXT_PRELOADER_CONTINUE,"Arial","#000","bold 34",a);d.addEventListener(ON_MOUSE_UP,this._onButStartRelease,this);d.setVisible(!1);m=new createjs.Shape;m.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);a.addChild(m);createjs.Tween.get(m).to({alpha:0},500).call(function(){createjs.Tween.removeTweens(m);a.removeChild(m)})};this._onButStartRelease=function(){s_oMain._onRemovePreloader()};this.refreshLoader=function(a){b.text=a+"%";100===a&&(d.setVisible(!0),b.visible=!1,g.visible=
!1);l.graphics.clear();a=Math.floor(a*c/100);l.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(g.x,g.y,a,h)};this._init()}
function CMain(c){var h,b=0,g=0,l=STATE_LOADING,m,f,n;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.framerate=30;navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=
!0);s_oSpriteLibrary=new CSpriteLibrary;m=new CPreloader};this.setLocalStorageLevel=function(a){var e=getItem(GAME_NAME+"_level");if(null===e||e<a)s_iLastLevel=a,saveItem(GAME_NAME+"_level",s_iLastLevel),trace("setLocalStorageLevel "+s_iLastLevel)};this.setLocalStorageScore=function(a,e){saveItem(GAME_NAME+"_score_level_"+e,a);trace("setLocalStorageScore "+a+" in level "+e)};this.clearLocalStorage=function(){s_iLastLevel=1;if(s_bStorageAvailable)for(var a=0;a<localStorage.length;){var e=localStorage.key(a);
-1!==e.indexOf(GAME_NAME)?localStorage.removeItem(e):a++}};this.getScoreTillLevel=function(a){if(!s_bStorageAvailable)return 0;for(var e=0,f=0;f<a-1;f++)e+=parseInt(getItem(GAME_NAME+"_score_level_"+(f+1)));return e};this.getScoreLevel=function(a){return getItem(GAME_NAME+"_score_level_"+(a+1))};this.getSavedLevel=function(){if(!s_bStorageAvailable)return 1;var a=getItem(GAME_NAME+"_level");return null===a?1:a};this.preloaderReady=function(){this._loadImages();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||
this._initSounds();h=!0};this.soundLoaded=function(){b++;m.refreshLoader(Math.floor(b/g*100))};this._initSounds=function(){var a=[];a.push({path:"./sounds/",filename:"game_completed",loop:!1,volume:1,ingamename:"game_completed"});a.push({path:"./sounds/",filename:"click",loop:!1,volume:1,ingamename:"click"});a.push({path:"./sounds/",filename:"game_over",loop:!1,volume:1,ingamename:"game_over"});a.push({path:"./sounds/",filename:"boing",loop:!1,volume:1,ingamename:"boing"});a.push({path:"./sounds/",
filename:"ball_lose",loop:!1,volume:1,ingamename:"ball_lose"});a.push({path:"./sounds/",filename:"fireball",loop:!0,volume:1,ingamename:"fireball"});a.push({path:"./sounds/",filename:"brick_crack",loop:!1,volume:1,ingamename:"brick_crack"});a.push({path:"./sounds/",filename:"brick_explosion",loop:!1,volume:1,ingamename:"brick_explosion"});a.push({path:"./sounds/",filename:"brick_metal",loop:!1,volume:1,ingamename:"brick_metal"});a.push({path:"./sounds/",filename:"power_up_bonus",loop:!1,volume:1,
ingamename:"power_up_bonus"});a.push({path:"./sounds/",filename:"power_up_malus",loop:!1,volume:1,ingamename:"power_up_malus"});a.push({path:"./sounds/",filename:"stage_clear",loop:!1,volume:1,ingamename:"stage_clear"});a.push({path:"./sounds/",filename:"bullet",loop:!1,volume:1,ingamename:"bullet"});a.push({path:"./sounds/",filename:"soundtrack",loop:!0,volume:1,ingamename:"soundtrack"});g+=a.length;s_aSounds=[];for(var e=0;e<a.length;e++)s_aSounds[a[e].ingamename]=new Howl({src:[a[e].path+a[e].filename+
".mp3",a[e].path+a[e].filename+".ogg"],autoplay:!1,preload:!0,loop:a[e].loop,volume:a[e].volume,onload:s_oMain.soundLoaded()})};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("bg_level_1","./sprites/bg_level_1.jpg");s_oSpriteLibrary.addSprite("paddle","./sprites/paddle.png");s_oSpriteLibrary.addSprite("paddle_magnet",
"./sprites/paddle_magnet.png");s_oSpriteLibrary.addSprite("cannons","./sprites/cannons.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("but_pause","./sprites/but_pause.png");s_oSpriteLibrary.addSprite("icon_audio","./sprites/icon_audio.png");s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("but_restart","./sprites/but_restart.png");s_oSpriteLibrary.addSprite("but_continue","./sprites/but_continue.png");s_oSpriteLibrary.addSprite("but_level",
"./sprites/but_level.png");s_oSpriteLibrary.addSprite("powerup_edge","./sprites/powerup_edge.png");s_oSpriteLibrary.addSprite("up_edges","./sprites/up_edges.png");s_oSpriteLibrary.addSprite("normal_ball","./sprites/normal_ball.png");s_oSpriteLibrary.addSprite("fire_ball","./sprites/fire_ball.png");s_oSpriteLibrary.addSprite("iron_ball","./sprites/iron_ball.png");s_oSpriteLibrary.addSprite("bullet","./sprites/bullet.png");s_oSpriteLibrary.addSprite("but_yes","./sprites/but_yes.png");s_oSpriteLibrary.addSprite("but_no",
"./sprites/but_no.png");s_oSpriteLibrary.addSprite("life","./sprites/life.png");s_oSpriteLibrary.addSprite("ctl_logo","./sprites/ctl_logo.png");s_oSpriteLibrary.addSprite("but_credits","./sprites/but_credits.png");s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");s_oSpriteLibrary.addSprite("but_clear_save","./sprites/but_clear_save.png");for(var a=0;a<TYPES_OF_BRICK;a++)s_oSpriteLibrary.addSprite("brick"+a,"./sprites/brick"+a+".png");for(a=0;a<TYPES_OF_BONUS;a++)s_oSpriteLibrary.addSprite("bonus"+
a,"./sprites/bonus"+a+".png");g+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){b++;m.refreshLoader(Math.floor(b/g*100))};this._onAllImagesLoaded=function(){};this._onRemovePreloader=function(){m.unload();try{saveItem("ls_available","ok"),s_iLastLevel=this.getSavedLevel()}catch(a){s_bStorageAvailable=!1}s_oSoundTrack=playSound("soundtrack",1,!0);this.gotoMenu()};this.gotoMenu=function(){new CMenu;l=STATE_MENU};this.levelSelected=function(a){s_iLevelSelected=
a;n.unload();a>=s_iLastLevel&&(s_iLastLevel=a);trace("iLevel "+a);s_oMain.gotoGame(a)};this.gotoGame=function(a){f=new CGame(d,a);l=STATE_GAME;$(s_oMain).trigger("game_start")};this.gotoLevelMenu=function(){n=new CLevelMenu(d);l=STATE_MENU};this.stopUpdate=function(){h=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block");!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||Howler.mute(!0)};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();h=!0;createjs.Ticker.paused=!1;$("#block_game").css("display",
"none");(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)&&s_bAudioActive&&Howler.mute(!1)};this.stopUpdateNoBlock=function(){h=!1;createjs.Ticker.paused=!0};this.startUpdateNoBlock=function(){s_iPrevTime=(new Date).getTime();h=!0;createjs.Ticker.paused=!1};this._update=function(a){if(!1!==h){var e=(new Date).getTime();s_iTimeElaps=e-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=e;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);l===STATE_GAME&&f.update();s_oStage.update(a)}};
s_oMain=this;var d=c;ENABLE_FULLSCREEN=c.fullscreen;ENABLE_CHECK_ORIENTATION=c.check_orientation;this.initContainer()}var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_iLastLevel=1,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundTrack=null,s_oCanvas,s_bFullscreen=!1,s_aSounds,s_bStorageAvailable=!0;
function CTextButton(c,h,b,g,l,m,f,n){var d,a,e,p,w,C,y,A,r,x,q,z;this._init=function(f,b,c,g,l,h,m,n){d=!1;p=[];w=[];z=createBitmap(c);a=c.width;e=c.height;var t=Math.ceil(m/20);x=new createjs.Text(g,m+"px "+l,"#000000");var C=x.getBounds();x.textAlign="center";x.lineWidth=.9*a;x.textBaseline="alphabetic";x.x=c.width/2+t;x.y=Math.floor(c.height/2)+C.height/3+t;q=new createjs.Text(g,m+"px "+l,h);q.textAlign="center";q.textBaseline="alphabetic";q.lineWidth=.9*a;q.x=c.width/2;q.y=Math.floor(c.height/
2)+C.height/3;r=new createjs.Container;r.x=f;r.y=b;r.regX=c.width/2;r.regY=c.height/2;s_bMobile||(r.cursor="pointer");r.addChild(z,x,q);!1!==n&&s_oStage.addChild(r);this._initListener()};this.unload=function(){r.off("mousedown",y);r.off("pressup",A);s_oStage.removeChild(r)};this.setVisible=function(a){r.visible=a};this.setAlign=function(a){q.textAlign=a;x.textAlign=a};this.enable=function(){d=!1;z.filters=[];z.cache(0,0,a,e)};this.disable=function(){d=!0;var f=(new createjs.ColorMatrix).adjustSaturation(-100).adjustBrightness(40);
z.filters=[new createjs.ColorMatrixFilter(f)];z.cache(0,0,a,e)};this._initListener=function(){y=r.on("mousedown",this.buttonDown);A=r.on("pressup",this.buttonRelease)};this.addEventListener=function(a,e,f){p[a]=e;w[a]=f};this.addEventListenerWithParams=function(a,e,f,d){p[a]=e;w[a]=f;C=d};this.buttonRelease=function(){d||(playSound("click",1,!1),r.scaleX=1,r.scaleY=1,p[ON_MOUSE_UP]&&p[ON_MOUSE_UP].call(w[ON_MOUSE_UP],C))};this.buttonDown=function(){d||(r.scaleX=.9,r.scaleY=.9,p[ON_MOUSE_DOWN]&&p[ON_MOUSE_DOWN].call(w[ON_MOUSE_DOWN]))};
this.setPosition=function(a,e){r.x=a;r.y=e};this.changeText=function(a){q.text=a;x.text=a};this.setX=function(a){r.x=a};this.setY=function(a){r.y=a};this.getButtonImage=function(){return r};this.getX=function(){return r.x};this.getY=function(){return r.y};this.getSprite=function(){return r};this._init(c,h,b,g,l,m,f,n);return this}
function CTextToggle(c,h,b,g,l,m,f,n,d){var a=1,e,p=!1,w,C,y,A,r,x,q,z;this._init=function(a,f,d,b,c,g,l,p,h){e=!1;w=[];C=[];z=createBitmap(d);var m=Math.ceil(l/20);q=new createjs.Text(b," "+l+"px "+c,"#000000");q.textAlign="center";q.textBaseline="alphabetic";var n=q.getBounds();q.x=d.width/2+m;q.y=Math.floor(d.height/2)+n.height/3+m-7;x=new createjs.Text(b," "+l+"px "+c,g);x.textAlign="center";x.textBaseline="alphabetic";n=x.getBounds();x.x=d.width/2;x.y=Math.floor(d.height/2)+n.height/3-7;r=new createjs.Container;
r.x=a;r.y=f;r.regX=d.width/2;r.regY=d.height/2;p||(a=new createjs.SpriteSheet({images:[d],frames:{width:d.width/2,height:d.height,regX:d.width/2/2,regY:d.height/2},animations:{state_true:[0],state_false:[1]}}),z=createSprite(a,"state_false",d.width/2/2,d.height/2,d.width/2,d.height),q.x=m,q.y=m+17,x.x=0,x.y=17,r.regX=0,r.regY=0);r.addChild(z,q,x);h.addChild(r);this._initListener()};this.unload=function(){r.off("mousedown",y);r.off("pressup",A);d.removeChild(r)};this.setVisible=function(a){r.visible=
a};this._initListener=function(){y=r.on("mousedown",this.buttonDown);A=r.on("pressup",this.buttonRelease)};this.addEventListener=function(a,e,f){w[a]=e;C[a]=f};this.buttonRelease=function(){e||p||(r.scaleX=1*a,r.scaleY=1*a,w[ON_MOUSE_UP]&&w[ON_MOUSE_UP].call(C[ON_MOUSE_UP]))};this.buttonDown=function(){e||p||(r.scaleX=.9*a,r.scaleY=.9*a,w[ON_MOUSE_DOWN]&&w[ON_MOUSE_DOWN].call(C[ON_MOUSE_DOWN]))};this.enable=function(){e=!1;n||z.gotoAndStop("state_true")};this.disable=function(){e=!0;n||z.gotoAndStop("state_false")};
this.setTextPosition=function(a,e){var d=Math.ceil(f/20);q.x=a+d;q.y=e+d;x.x=a;x.y=e};this.setText=function(a){x.text=a;q.text=a};this.setPosition=function(a,e){r.x=a;r.y=e};this.setX=function(a){r.x=a};this.setY=function(a){r.y=a};this.getButtonImage=function(){return r};this.getX=function(){return r.x};this.getY=function(){return r.y};this.block=function(a){p=a};this.setScale=function(e){a=e;r.scaleX=e;r.scaleY=e};this.setScaleX=function(a){z.scaleX=a};this._init(c,h,b,g,l,m,f,n,d);return this}
function CToggle(c,h,b,g){var l,m,f,n=[],d;this._init=function(a,e,b,c){m=[];f=[];var g=new createjs.SpriteSheet({images:[b],frames:{width:b.width/2,height:b.height,regX:b.width/2/2,regY:b.height/2},animations:{state_true:[0],state_false:[1]}});l=c;d=createSprite(g,"state_"+l,b.width/2/2,b.height/2,b.width/2,b.height);d.mouseEnabled=!0;d.x=a;d.y=e;d.stop();s_bMobile||(d.cursor="pointer");s_oStage.addChild(d);this._initListener()};this.unload=function(){d.off("mousedown",this.buttonDown);d.off("pressup",
this.buttonRelease);d.mouseEnabled=!1;s_oStage.removeChild(d)};this._initListener=function(){d.on("mousedown",this.buttonDown);d.on("pressup",this.buttonRelease)};this.addEventListener=function(a,e,d){m[a]=e;f[a]=d};this.addEventListenerWithParams=function(a,e,d,b){m[a]=e;f[a]=d;n=b};this.setActive=function(a){l=a;d.gotoAndStop("state_"+l)};this.buttonRelease=function(){d.scaleX=1;d.scaleY=1;playSound("click",1,!1);l=!l;d.gotoAndStop("state_"+l);m[ON_MOUSE_UP]&&m[ON_MOUSE_UP].call(f[ON_MOUSE_UP],
n)};this.buttonDown=function(){d.scaleX=.9;d.scaleY=.9;m[ON_MOUSE_DOWN]&&m[ON_MOUSE_DOWN].call(f[ON_MOUSE_DOWN],n)};this.setPosition=function(a,e){d.x=a;d.y=e};this.setVisible=function(a){d.visible=a};this._init(c,h,b,g)}
function CNumToggle(c,h,b,g){var l,m,f,n,d,a,e,p=[];this._init=function(b,c,g,h){m=!1;f=[];n=[];d=new createjs.Container;d.x=b;d.y=c;h.addChild(d);b=s_oSpriteLibrary.getSprite("num_button");c={images:[b],framerate:5,frames:{width:b.width/2,height:b.height,regX:b.width/2/2,regY:b.height/2},animations:{state_true:[0],state_false:[1]}};c=new createjs.SpriteSheet(c);l=!1;a=createSprite(c,"state_"+l,b.width/2/2,b.height/2,b.width/2,b.height);a.stop();b=s_oSpriteLibrary.getSprite("ball");c={images:[b],
frames:{width:b.width/NUM_DIFFERENT_BALLS,height:b.height,regX:b.width/NUM_DIFFERENT_BALLS/2,regY:b.height/2},animations:{red:[0],green:[1],cyan:[0],violet:[1],blue:[1]}};c=new createjs.SpriteSheet(c);e=createSprite(c,"red",b.width/NUM_DIFFERENT_BALLS/2,b.height/2,b.width/NUM_DIFFERENT_BALLS,b.height);e.gotoAndStop(0);e.visible=!1;s_bMobile||(d.cursor="pointer");d.addChild(a,e);this._initListener()};this.unload=function(){d.off("mousedown",this.buttonDown);d.off("pressup",this.buttonRelease);g.removeChild(d)};
this._initListener=function(){d.on("mousedown",this.buttonDown);d.on("pressup",this.buttonRelease)};this.addEventListener=function(a,e,b){f[a]=e;n[a]=b};this.addEventListenerWithParams=function(a,e,b,d){f[a]=e;n[a]=b;p=d};this.setActive=function(e){l=e;a.gotoAndStop("state_"+l)};this.buttonRelease=function(){m||(playSound("click",1,!1),l=!l,a.gotoAndStop("state_"+l),f[ON_MOUSE_UP]&&f[ON_MOUSE_UP].call(n[ON_MOUSE_UP],p))};this.buttonDown=function(){m||f[ON_MOUSE_DOWN]&&f[ON_MOUSE_DOWN].call(n[ON_MOUSE_DOWN],
p)};this.setPosition=function(a,e){d.x=a;d.y=e};this.getGlobalPosition=function(){return{x:d.localToGlobal(0,0).x,y:d.localToGlobal(0,0).y}};this.block=function(a){m=a};this.setExtracted=function(a,f){e.visible=a;e.gotoAndStop(f)};this.highlight=function(){a.gotoAndPlay(0)};this.stopHighlight=function(){a.gotoAndStop(1)};this._init(c,h,b,g)}
function CGfxButton(c,h,b,g){var l,m,f,n=[],d,a,e,p;this._init=function(a,b,d){l=1;m=[];f=[];e=createBitmap(d);e.x=a;e.y=b;e.regX=d.width/2;e.regY=d.height/2;s_bMobile||(e.cursor="pointer");g.addChild(e);p=!1;this._initListener()};this.unload=function(){e.off("mousedown",d);e.off("pressup",a);g.removeChild(e)};this.setVisible=function(a){e.visible=a};this._initListener=function(){d=e.on("mousedown",this.buttonDown);a=e.on("pressup",this.buttonRelease)};this.addEventListener=function(a,e,b){m[a]=e;
f[a]=b};this.addEventListenerWithParams=function(a,e,b,d){m[a]=e;f[a]=b;n=d};this.buttonRelease=function(){p||(e.scaleX=l,e.scaleY=l,playSound("click",1,!1),m[ON_MOUSE_UP]&&m[ON_MOUSE_UP].call(f[ON_MOUSE_UP],n))};this.buttonDown=function(){p||(e.scaleX=.9*l,e.scaleY=.9*l,m[ON_MOUSE_DOWN]&&m[ON_MOUSE_DOWN].call(f[ON_MOUSE_DOWN],n))};this.setScale=function(a){l=a;e.scaleX=a;e.scaleY=a};this.setPosition=function(a,f){e.x=a;e.y=f};this.setX=function(a){e.x=a};this.setY=function(a){e.y=a};this.getButtonImage=
function(){return e};this.getX=function(){return e.x};this.getY=function(){return e.y};this.block=function(a){p=a};this._init(c,h,b);return this}
function CMenu(){var c,h,b,g,l,m,f,n,d,a,e,p,w,C,y,A,r=null,x=null;this._init=function(){d=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(d);var q=s_oSpriteLibrary.getSprite("but_play");a=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/2+250,q,s_oStage);a.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)q=s_oSpriteLibrary.getSprite("icon_audio"),l=CANVAS_WIDTH-q.width/2+15,m=q.height/2+20,p=new CToggle(l,m,q,s_bAudioActive),
p.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);q=s_oSpriteLibrary.getSprite("but_credits");b=q.width/2+20;g=q.height/2+20;w=new CGfxButton(b,g,q,s_oStage);w.addEventListener(ON_MOUSE_UP,this._onCreditsBut,this);q=window.document;var z=q.documentElement;r=z.requestFullscreen||z.mozRequestFullScreen||z.webkitRequestFullScreen||z.msRequestFullscreen;x=q.exitFullscreen||q.mozCancelFullScreen||q.webkitExitFullscreen||q.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(r=!1);r&&screenfull.enabled&&(q=
s_oSpriteLibrary.getSprite("but_fullscreen"),c=b+q.width/2+10,h=g,C=new CToggle(c,h,q,s_bFullscreen,!0),C.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));q=s_oSpriteLibrary.getSprite("but_clear_save");f=q.width/2+20;n=CANVAS_HEIGHT-q.height/2-20;y=new CGfxButton(f,n,q,s_oStage);y.addEventListener(ON_MOUSE_UP,this._onClearSave,this);A=new CAreYouSurePanel;A.addEventListener(ON_BUT_YES_DOWN,this._onConfirmClear,this);s_bStorageAvailable||new CAlertSavingBox(TEXT_ERR_LS,s_oStage);e=new createjs.Shape;
e.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(e);createjs.Tween.get(e).to({alpha:0},1E3).call(function(){s_oStage.removeChild(e)});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){a.unload();a=null;y.unload();s_oStage.removeChild(d);d=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)p.unload(),p=null;r&&screenfull.enabled&&C.unload();w.unload();s_oMenu=null};this.refreshButtonPos=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||
p.setPosition(l-s_iOffsetX,m+s_iOffsetY);r&&screenfull.enabled&&C.setPosition(c+s_iOffsetX,h+s_iOffsetY);w.setPosition(b+s_iOffsetX,g+s_iOffsetY);y.setPosition(f+s_iOffsetX,n-s_iOffsetY)};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onButPlayRelease=function(){this.unload();s_oMain.gotoLevelMenu()};this._onCreditsBut=function(){new CCreditsPanel};this.resetFullscreenBut=function(){r&&screenfull.enabled&&C.setActive(s_bFullscreen)};this._onFullscreenRelease=
function(){s_bFullscreen?x.call(window.document):r.call(window.document.documentElement);sizeHandler()};this._onClearSave=function(){A.show(TEXT_CONFIRM_CLEAR_SAVINGS)};this._onConfirmClear=function(){s_oMain.clearLocalStorage()};s_oMenu=this;this._init()}var s_oMenu=null;
function CGame(c,h){var b,g,l,m,f,n,d,a,e={},p,w,C=0,y,A,r,x,q,z,H,P,N,J,t,R,L,B,D,ba,Z,S,T,ca,ea,k,U,fa,V,E,u,F,K,v,ia,Q,O,aa,M,ha,da,qa,W,ka,I,X,ra,la,na,Y,Ba,Ca,Da,Ea,ta,oa,pa,ua,va,wa,xa,ya,G,ja,ma,sa;this._init=function(d){m=!1;var c=s_oSpriteLibrary.getSprite("normal_ball");U=0;H=CANVAS_WIDTH/2;f=[];n=[];k=[];fa=SPACE_BETWEEN_BRICKS;t=w=0;var Fa=s_oSpriteLibrary.getSprite("brick0");P=Fa.width/2;N=Fa.height/2;Y=1;p=c.height/2+OFFSET_RADIUS_BALL;l=d;I=s_oMain.getScoreTillLevel(l);ma=X=0;ra=MAX_TIME_SHOT_BONUS;
ka=LIFE;ca=new CSettingsLevel;x=[];r=[];A=[];y=[];q=[];z=[];this.createPadding(CANVAS_WIDTH/2);v=da=ha=M=aa=O=Q=!1;sa=K=0;d=OFFSETEDGELEFT+p;Ba=CANVAS_WIDTH+(-OFFSETEDGERIGHT-p);Ca=d;b=createBitmap(s_oSpriteLibrary.getSprite("bg_level_1"));s_oStage.addChild(b);b.addEventListener("click",this.launchBall);s_oStage.setChildIndex(b,0);ea=[];B=N+p+OFFSET_HEIGHT_BRICK;D=P+p+OFFSET_WIDTH_BRICK;ba=B+OFFSET_Y_BRICK;Z=D+OFFSET_X_BRICK;T=EDGE_OFFSET+e.x;S=CANVAS_WIDTH-EDGE_OFFSET-e.x;T=EDGE_OFFSET+e.x;Da=2*
N+OFFSET_BRICK_Y_POS;Ea=2*P;ta=OFFSET_BRICK_SECTION_X+OFFSET_DETECTION_BRICK_SECTION_X;ia=TIME_REFLECT_IRON_BRICK;g=new CInterface(I);this.createABall(0,a.x,a.y-p-e.y,c,!0);this.createLevel();1===l?g.help(l):g.showNumLevel(l-1);g.numLevel(l);na=!0;V=!1;la=0;setVolume("soundtrack",.3)};this.launchBall=function(){!1===V&&!1===m?(a.x>H?(a.x-=H,ja=-(a.x/H)):ja=a.x/H,f[0].setPosition(null,f[0].getY()-3),f[0].setDirection(ja,-1),f[0].setInfoData("OnPad",!1),V=!0):!0===M&&s_oGame.launchUnmagneticBall()};
this.createLevel=function(){this.setLevelBrick();$(s_oMain).trigger("start_level",l);ea=ca.createBonusOccurance(l)};this.createABall=function(a,e,d,b,c,g,l){f[a]=new CBall(e,d,b,g,l,Y,O,p);f[a].setInfoData("ID",a);f[a].setInfoData("OnPad",c);f[a].setInfoData("Collision",0);f[a].changeRotation();!0===aa&&f[a].downFloor(!0);!0===c&&(V=!1)};this.generateABonus=function(a,e){var f=Math.floor(Math.random()*ea.length),d=s_oSpriteLibrary.getSprite("bonus"+ea[f]);k.push(new CBonus(a,e,d,ea[f]));k[U].setInfoData("ID",
U);U++};this.createPadding=function(f){a&&s_oStage.removeChild();var d=s_oSpriteLibrary.getSprite("paddle"),b=new createjs.SpriteSheet({images:[d],frames:{width:d.width/7,height:d.height/2,regX:d.width/2/7,regY:d.height/2/7},animations:{small:{frames:[0]},normal:{frames:[6]},big:{frames:[12]},StoN:{frames:[1,2,3,4,5,6]},NtoB:{frames:[7,8,9,10,11,12]},BtoN:{frames:[11,10,9,8,7,6]},NtoS:{frames:[5,4,3,2,1,0]}}});a=createSprite(b,"normal",d.width/2/7,d.height/2/2,d.width/7,d.height/2);a.x=f;a.y=HEIGHT_OF_PADDLE;
s_oStage.addChild(a);s_oStage.setChildIndex(a,3);e={x:PADDLE_DIMENSION[1]/2,y:d.height/2/2-OFFSET_PAD_Y}};this.setLevelBrick=function(){var a=BRICKS_LEVEL_POSITION[l-1],e=0,d=0;R=a.length/MAX_BRICK_FOR_ROW;for(var f=0;f<R;f++)for(var b=0;b<MAX_BRICK_FOR_ROW;b++){if(-1!==a[e]){var c=s_oSpriteLibrary.getSprite("brick"+a[e]);n[d]=new CBrick(CANVAS_WIDTH/2-250-fa+(Ea+fa)*b,CANVAS_HEIGHT/2-310+(Da+fa)*f,c,BRICKS_RESISTANCE[a[e]],BRICKS_DESTRUCTIBLE[a[e]]);n[d].setInfoData("resistance",BRICKS_RESISTANCE[a[e]]);
n[d].setInfoData("score",BRICKS_SCORE[a[e]]);n[d].setInfoData("destructible",BRICKS_DESTRUCTIBLE[a[e]]);n[d].setChildIndex(4);!0===BRICKS_DESTRUCTIBLE[a[e]]&&t++;d++}e++}w=n[d-1].getY()+OFFSET_DIAGRAM_CHECK+N;this.createBricksSections()};this.loseBall=function(d){this.unloadBall(d);1>f.length&&(ka--,g.refreshBallLife(ka),!0===Q?this.deactiveLargePad():!0===da&&this.deactiveSmallPad(),!0===ha?K=0:!0===M&&this.deactiveMagnetic(),!0===aa&&this.deactiveFloor(),!0===O&&this.stopFireSound(),M=aa=O=Q=!1,
Y=1,this.checkOtherActiveBonus(),0<ka?(V=!1,d=s_oSpriteLibrary.getSprite("normal_ball"),this.createABall(0,a.x,a.y-p-e.y,d,!0)):g.gameOver(I));playSound("ball_lose",1,!1)};this.setPause=function(a){m=a};this.createBricksSections=function(){var a=0,e=0,d=0,f=0,b=0,c=0;J=1===R%2?n[Math.floor(n.length/2)].getY()+2*N+OFFSET_CENTER_Y_DIAGRAM:n[Math.floor(n.length/2)].getY()-N+OFFSET_CENTER_Y_DIAGRAM;L=H+B+Math.floor(fa/2)+OFFSET_CENTER_X_DIAGRAM;oa=L+ta;pa=L-ta;ua=L+OFFSET_BRICK_SECTION_X;va=L-OFFSET_BRICK_SECTION_X;
wa=J+OFFSET_BRICK_SECTION_Y;xa=J+OFFSET_DETECTION_BRICK_SECTION_Y;ya=J-OFFSET_DETECTION_BRICK_SECTION_Y;for(var g=0;g<n.length;g++)if(n[g].getX()<=L-OFFSET_BRICK_SECTION_X&&n[g].getY()<J-OFFSET_BRICK_SECTION_Y)A[e]=n[g],e++;else if(n[g].getX()>=L+OFFSET_BRICK_SECTION_X&&n[g].getY()<J-OFFSET_BRICK_SECTION_Y)y[a]=n[g],a++;else if(n[g].getX()<=L-OFFSET_BRICK_SECTION_X&&n[g].getY()>J+OFFSET_BRICK_SECTION_Y)x[f]=n[g],f++;else if(n[g].getX()>=L+OFFSET_BRICK_SECTION_X&&n[g].getY()>J+OFFSET_BRICK_SECTION_Y)r[d]=
n[g],d++;else if(n[g].getX()<=L+OFFSET_BRICK_SECTION_X&&n[g].getX()>=L-OFFSET_BRICK_SECTION_X)q[b]=n[g],b++;else if(n[g].getY()<=J+OFFSET_BRICK_SECTION_Y&&n[g].getY()>=J-OFFSET_BRICK_SECTION_Y&&n[g]&&n[g].getX()>=L+OFFSET_BRICK_SECTION_X||n[g].getX()<=L-OFFSET_BRICK_SECTION_X)z[c]=n[g],c++};this.onExit=function(){s_oGame.unload();s_oMain.gotoMenu();$(s_oMain).trigger("end_level",l);$(s_oMain).trigger("end_session");$(s_oMain).trigger("show_interlevel_ad");setVolume("soundtrack",1)};this.bonusLargePad=
function(){X+=BONUS_SCORE.s0;I+=BONUS_SCORE.s0;g.refreshScore(I);!0===da?this.deactiveSmallPad():(!0===M?this.deactiveMagnetic():G&&(K=0,G.gotoAndPlay("go"),G.on("animationend",function(){s_oStage.removeChild(G);G=null})),this.audioPowerUpBonus(),Q||(e.x=PADDLE_DIMENSION[2]/2,a.gotoAndPlay("NtoB"),a.on("animationend",function(){a.gotoAndStop("big")}),Q=!0,S=CANVAS_WIDTH-EDGE_OFFSET-e.x,T=EDGE_OFFSET+e.x))};this.bonusSmallPad=function(){X+=BONUS_SCORE.s9;I+=BONUS_SCORE.s9;g.refreshScore(I);this.audioPowerUpMalus();
!0===Q?this.deactiveLargePad():(!0===M?this.deactiveMagnetic():G&&(K=0,G.gotoAndPlay("go"),G.on("animationend",function(){s_oStage.removeChild(G);G=null})),da||(e.x=PADDLE_DIMENSION[0]/2,a.gotoAndPlay("NtoS"),a.on("animationend",function(){a.gotoAndStop("small")}),da=!0,S=CANVAS_WIDTH-EDGE_OFFSET-e.x,T=EDGE_OFFSET+e.x))};this.bonusMultiBall=function(){X+=BONUS_SCORE.s5;I+=BONUS_SCORE.s5;g.refreshScore(I);if(!(f.length>=MAX_BALL_SPAWN)){this.audioPowerUpBonus();var a=0;var e=f.length+BONUS_MULTI_BALL;
var d=f.length;var b=!1===O&&!1===M?s_oSpriteLibrary.getSprite("normal_ball"):!0===O?s_oSpriteLibrary.getSprite("fire_ball"):s_oSpriteLibrary.getSprite("iron_ball");for(var c=d;c<d+e;c++)0===a%2?this.createABall(c,f[a].getX(),f[a].getY(),b,!1,1,-1):this.createABall(c,f[a].getX(),f[a].getY(),b,!1,-1,1),a++}};this.bonusFireBall=function(){X+=BONUS_SCORE.s1;I+=BONUS_SCORE.s1;g.refreshScore(I);E=BONUS_TIME.t1;if(!0!==O){for(var e=s_oSpriteLibrary.getSprite("fire_ball"),d=0;d<f.length;d++)f[d].changeSprite(e,
"fire");O=!0;!0===M&&(s_oStage.removeChild(a),this.createPadding(a.x),this.launchUnmagneticBall(),M=!1);v=!0;playSound("fireball",1,!0);this.audioPowerUpBonus()}};this.createFloor=function(){var a=s_oSpriteLibrary.getSprite("powerup_edge");W=createBitmap(a);W.x=H;W.y=CANVAS_HEIGHT+a.height/2;W.regX=a.width/2;W.regY=a.height/2;s_oStage.addChild(W);s_oStage.setChildIndex(W,s_oStage.numChildren-1);createjs.Tween.get(W).to({y:940},800,createjs.Ease.backOut)};this.bonusMagnetic=function(){X+=BONUS_SCORE.s3;
I+=BONUS_SCORE.s3;g.refreshScore(I);F=BONUS_TIME.t3;this.audioPowerUpBonus();if(!0!==M){for(var e=s_oSpriteLibrary.getSprite("iron_ball"),d=0;d<f.length;d++)f[d].changeSprite(e,"magnetic");!0===Q?(a.gotoAndPlay("BtoN"),a.on("animationend",function(){s_oStage.removeChild(a);s_oGame.createMagneticPad(a.x)}),Q=!1):!0===da?(a.gotoAndPlay("StoN"),a.on("animationend",function(){s_oStage.removeChild(a);s_oGame.createMagneticPad(a.x)}),da=!1):G?(K=0,G.gotoAndPlay("go"),G.on("animationend",function(){s_oStage.removeChild(G);
G=null;s_oStage.removeChild(a);s_oGame.createMagneticPad(a.x)})):this.createMagneticPad(a.x);!0===O&&(O=!1,this.stopFireSound());v=M=!0}};this.createMagneticPad=function(d){s_oStage.removeChild(a);var f=s_oSpriteLibrary.getSprite("paddle_magnet"),b=new createjs.SpriteSheet({images:[f],frames:{width:f.width/5,height:f.height/2,regX:(f.width+REG_X_OFFSET_PADDLE_MAGNETIC)/2/5,regY:(f.height+REG_Y_OFFSET_PADDLE_MAGNETIC)/2/7},animations:{magnetic:[0,9,"magnetic",.5]}});a=createSprite(b,"magnetic",(f.width+
REG_X_OFFSET_PADDLE_MAGNETIC)/2/5,(f.height+REG_Y_OFFSET_PADDLE_MAGNETIC)/2/2,f.width/5,f.height/2);a.x=d;a.y=HEIGHT_OF_PADDLE;s_oStage.addChild(a);e.x=PADDLE_DIMENSION[1]/2;S=CANVAS_WIDTH-EDGE_OFFSET-e.x;T=EDGE_OFFSET+e.x};this.bonusLife=function(){X+=BONUS_SCORE.s4;I+=BONUS_SCORE.s4;g.refreshScore(I);g.refreshBallLife(ka);ka++;this.audioPowerUpBonus()};this.bonusSlowBall=function(){X+=BONUS_SCORE.s7;I+=BONUS_SCORE.s7;g.refreshScore(I);for(var a=0;a<f.length;a++)f[a].setVelocityRate(Y);1>Y?this.audioPowerUpMalus():
this.audioPowerUpBonus();Y>MIN_VELOCITY_LIMIT&&(Y-=SPEED_DOWN_BALL);Y<MIN_VELOCITY_LIMIT&&(Y=MIN_VELOCITY_LIMIT)};this.bonusFastBall=function(){X+=BONUS_SCORE.s8;I+=BONUS_SCORE.s8;g.refreshScore(I);if(Y<MAX_VELOCITY_LIMIT){Y+=SPEED_UP_BALL;for(var a=0;a<f.length;a++)f[a].setVelocityRate(Y);1<Y?this.audioPowerUpMalus():this.audioPowerUpBonus()}};this.bonusShot=function(){X+=BONUS_SCORE.s6;I+=BONUS_SCORE.s6;g.refreshScore(I);this.audioPowerUpBonus();K=BONUS_TIME.t6;!1===ha&&(ha=!0,qa=s_oSpriteLibrary.getSprite("bullet"),
d=[],!0===Q?(a.gotoAndPlay("BtoN"),a.on("animationend",function(){a.gotoAndStop("normal")}),Q=!1):!0===da?(a.gotoAndPlay("StoN"),a.on("animationend",function(){a.gotoAndStop("normal")}),da=!1):!0===M&&this.deactiveMagnetic(),G?(G.gotoAndPlay("come"),G.on("animationend",function(){G.gotoAndStop(5)})):this.createCannons());v=!0};this.bonusFloor=function(){X+=BONUS_SCORE.s2;I+=BONUS_SCORE.s2;g.refreshScore(I);u=BONUS_TIME.t2;if(!0!==aa){W||this.createFloor();for(var a=0;a<f.length;a++)f[a].downFloor(!0)}v=
aa=!0;this.audioPowerUpBonus()};this.createCannons=function(){var d=s_oSpriteLibrary.getSprite("cannons"),f=new createjs.SpriteSheet({images:[d],frames:{width:d.width/3,height:d.height/2,regX:d.width/2/3,regY:d.height/2/2},animations:{come:{frames:[0,1,2,3,4,5],speed:.5},go:{frames:[5,4,3,2,1,0],speed:.5}}});G=createSprite(f,"come",d.width/2/3,d.height/2/2,d.width/3,d.height/2);G.x=a.x;G.y=a.y+OFFSET_CANNONS_Y_POS;s_oStage.addChild(G);G.on("animationend",function(){G.gotoAndStop(5)});s_oStage.setChildIndex(G,
5);e.x=(PADDLE_DIMENSION[1]+OFFSET_DIM_X_CANNONS)/2;S=CANVAS_WIDTH-EDGE_OFFSET-e.x;T=EDGE_OFFSET+e.x};this.launchUnmagneticBall=function(){for(var a=0;a<f.length;a++)if(!0===f[a].getInfoData("OnPad")){var d=f[a].getInfoData("Collision")/e.x;d=Math.sin(d);f[a].setPosition(null,f[a].getY()-2);f[a].changeDirection(-d,-1,!1,"launch");f[a].setInfoData("OnPad",!1);f[a].changeRotation()}};this.unload=function(){g.unload();for(var a=0;a<f.length;a++)f[a].unload();for(a=0;a<k.length;a++)k[a].unload();createjs.Tween.removeAllTweens();
s_oStage.removeAllChildren()};this.__updatePhysics=function(d){var b=1/createjs.Ticker.framerate/za;a.x=s_oStage.mouseX;a.x<T&&(a.x=T);a.x>S&&(a.x=S);G&&(G.x=a.x);for(var c=0;c<f.length;c++)if(!1===f[c].getInfoData("OnPad")){var g=f[c].getX(),l=f[c].getY();f[c].update(d);if(g>a.x-e.x&&g<a.x+e.x&&l>a.y-e.y-p&&l<a.y+e.y+p){if(!1===M){if(0===ja){var h=a.x-g;h/=e.x;f[c].setPosition(null,l-1);ja=Math.sin(h);f[c].changeDirection(-ja,-1,!0);f[c].changeRotation()}ja=0}else{h=a.x-f[c].getX();f[c].setInfoData("Collision",
h);!1===f[c].getInfoData("OnPad")&&(f[c].setPosition(null,a.y-e.y-p),f[c].setInfoData("OnPad",!0));break}this.audioBoing()}if(l<w){if(g<oa&&l>wa)for(h=0;h<x.length;h++){if(g>x[h].getX()-D&&g<x[h].getX()+D&&l>x[h].getY()-B&&l<x[h].getY()+B){var k=x[h].getX(),m=x[h].getY();this.gestureBricks(x,h,k,m);this.ballBounce(c,g,l,k,m);break}}else if(g>pa&&l>wa)for(h=0;h<r.length;h++){if(g>r[h].getX()-D&&g<r[h].getX()+D&&l>r[h].getY()-B&&l<r[h].getY()+B){k=r[h].getX();m=r[h].getY();this.gestureBricks(r,h,k,
m);this.ballBounce(c,g,l,k,m);break}}else if(g<oa&&l<J)for(h=0;h<A.length;h++)g>A[h].getX()-D&&g<A[h].getX()+D&&l>A[h].getY()-B&&l<A[h].getY()+B&&(k=A[h].getX(),m=A[h].getY(),this.gestureBricks(A,h,k,m),this.ballBounce(c,g,l,k,m));else if(g>pa&&l<J)for(h=0;h<y.length;h++)if(g>y[h].getX()-D&&g<y[h].getX()+D&&l>y[h].getY()-B&&l<y[h].getY()+B){k=y[h].getX();m=y[h].getY();this.gestureBricks(y,h,k,m);this.ballBounce(c,g,l,k,m);break}if(g>va&&g<ua)for(h=0;h<q.length;h++)if(g>q[h].getX()-D&&g<q[h].getX()+
D&&l>q[h].getY()-B&&l<q[h].getY()+B){k=q[h].getX();m=q[h].getY();this.gestureBricks(q,h,k,m);this.ballBounce(c,g,l,k,m);break}if(l<xa&&l>ya)for(h=0;h<z.length;h++)if(g>z[h].getX()-D&&g<z[h].getX()+D&&l>z[h].getY()-B&&l<z[h].getY()+B){k=z[h].getX();m=z[h].getY();this.gestureBricks(z,h,k,m);this.ballBounce(c,g,l,k,m);break}}}else f[c].setPosition(a.x-f[c].getInfoData("Collision"),null),f[c].getX()>Ba?f[c].setInfoData("Collision",f[c].getInfoData("Collision")+1):f[c].getX()<Ca&&f[c].setInfoData("Collision",
f[c].getInfoData("Collision")-1);this.timeBonus(b);if(0<ia)ia-=b;else for(c=0;c<n.length;c++)!1===n[c].getInfoData("destructible")&&(n[c].reflectBrick(),n[c].setInfoData("Reflect",!0)),ia=TIME_REFLECT_IRON_BRICK;0<ma&&(ma-=b);0!==U&&this.bonusGesture()};this.allBrickDestroyed=function(){0<t||(this.setPause(!0),g.levelComplete(l,I),sa++,sa===NUM_LEVELS_FOR_ADS&&(sa=0,$(s_oMain).trigger("show_interlevel_ad")),$(s_oMain).trigger("end_level",l),$(s_oMain).trigger("save_score",I),s_oMain.setLocalStorageLevel(l+
1),s_oMain.setLocalStorageScore(X,l),!0===O&&this.stopFireSound())};this.stopFireSound=function(){stopSound("fireball")};this.timeBonus=function(f){!0===v&&(!0===O?0<E?E-=f:(this.deactiveFireBall(),this.checkOtherActiveBonus()):!0===M&&(0<F?F-=f:(this.deactiveMagnetic(),this.checkOtherActiveBonus())),!0===aa&&(0<u?u-=f:(this.deactiveFloor(),this.checkOtherActiveBonus())),!0===ha&&(0<K&&(K-=f,--ra,0>ra&&(!0===na?(d.push(new CBullet(a.x-e.x,a.y-e.y,qa)),na=!1):(d.push(new CBullet(a.x+e.x,a.y-e.y,qa)),
na=!0),d[la].setIndex(la),ra=MAX_TIME_SHOT_BONUS,la++,this.audioBullet())),1>d.length&&.1>K?(this.deactiveShot(),this.checkOtherActiveBonus()):this.detectiveCollisionBullet()))};this.nextLevel=function(){this.unloadLevel();l++;this.createLevel();var d=s_oSpriteLibrary.getSprite("normal_ball");Y=1;this.createABall(0,a.x,a.y-p-e.y,d,!0);na=!0;V=!1;X=la=0;g.showNumLevel(l);g.numLevel(l)};this.audioBrickExplosion=function(){playSound("brick_explosion",1,!1)};this.audioPowerUpBonus=function(){playSound("power_up_bonus",
1,!1)};this.audioPowerUpMalus=function(){playSound("power_up_malus",1,!1)};this.audioBrickMetal=function(){playSound("brick_metal",1,!1)};this.audioBullet=function(){playSound("bullet",1,!1)};this.audioBoing=function(){playSound("boing",1,!1)};this.ballBounce=function(a,d,e,b,c){!0===O||0<ma||(d>b+Z||d<b-Z&&e>c-ba&&e<c+ba?(d>b?(f[a].changeDirection(-1,1,!1,"side"),f[a].setPosition(f[a].getX()+3,null)):(f[a].changeDirection(-1,1,!1,"side"),f[a].setPosition(f[a].getX()-3,null)),ma=TIME_BOUNCE_BALL):
d>b-D&&d<b+D&&e>c-B&&e<c+B&&(e>c?(f[a].changeDirection(1,1,!1,"base"),f[a].setPosition(null,f[a].getY()+3)):(f[a].changeDirection(1,-1,!1,"base"),f[a].setPosition(null,f[a].getY()-3)),ma=TIME_BOUNCE_BALL,f[a].changeRotation()),this.audioBoing())};this.gestureBricks=function(a,d,e,f){!0===a[d].getInfoData("destructible")||!0===O?0===a[d].getInfoData("resistance")?(X+=a[d].getInfoData("score"),I+=a[d].getInfoData("score"),g.refreshScore(I),!0===a[d].getInfoData("destructible")&&(t--,this.allBrickDestroyed()),
!1===a[d].getInfoData("Effect")?a[d].unload():(a[d].animBrick("destroyed"),this.audioBrickExplosion()),this.randomBonus(e,f),a.splice(d,1)):(a[d].setInfoData("resistance",a[d].getInfoData("resistance")-1),a[d].damageBrick(a[d].getInfoData("resistance")),playSound("brick_crack",1,!1)):(a[d].reflectBrick(),a[d].setInfoData("Reflect",!0),this.audioBrickMetal())};this.detectiveCollisionBullet=function(){for(var a=0;a<d.length;a++){var e=d[a].getX(),f=d[a].getY();d[a].update();if(f<w){if(e<oa&&f>J)for(var b=
0;b<x.length;b++){if(e>x[b].getX()-D&&e<x[b].getX()+D&&f>x[b].getY()-B&&f<x[b].getY()+B){var c=x[b].getX(),g=x[b].getY();this.gestureBricks(x,b,c,g);this.unloadBullet(d[a].getIndex());break}}else if(e>pa&&f>J)for(b=0;b<r.length;b++){if(e>r[b].getX()-D&&e<r[b].getX()+D&&f>r[b].getY()-B&&f<r[b].getY()+B){c=r[b].getX();g=r[b].getY();this.gestureBricks(r,b,c,g);this.unloadBullet(d[a].getIndex());break}}else if(e<oa&&f<J)for(b=0;b<A.length;b++)e>A[b].getX()-D&&e<A[b].getX()+D&&f>A[b].getY()-B&&f<A[b].getY()+
B&&(c=A[b].getX(),g=A[b].getY(),this.gestureBricks(A,b,c,g),this.unloadBullet(d[a].getIndex()));else if(e>pa&&f<J)for(b=0;b<y.length;b++)if(e>y[b].getX()-D&&e<y[b].getX()+D&&f>y[b].getY()-B&&f<y[b].getY()+B){c=y[b].getX();g=y[b].getY();this.gestureBricks(y,b,c,g);this.unloadBullet(d[a].getIndex());break}if(e>va&&e<ua)for(b=0;b<q.length;b++)if(e>q[b].getX()-D&&e<q[b].getX()+D&&f>q[b].getY()-B&&f<q[b].getY()+B){c=q[b].getX();g=q[b].getY();this.gestureBricks(q,b,c,g);this.unloadBullet(d[a].getIndex());
break}if(f<xa&&f>ya)for(b=0;b<z.length;b++)if(e>z[b].getX()-D&&e<z[b].getX()+D&&f>z[b].getY()-B&&f<z[b].getY()+B){c=z[b].getX();g=z[b].getY();this.gestureBricks(z,b,c,g);this.unloadBullet(d[a].getIndex());break}}}};this.deactiveFireBall=function(){for(var a=s_oSpriteLibrary.getSprite("normal_ball"),b=0;b<f.length;b++)f[b].changeSprite(a,"normal");O=!1;this.stopFireSound()};this.deactiveLargePad=function(){a.gotoAndPlay("BtoN");a.on("animationend",function(){a.gotoAndStop("normal")});e.x=PADDLE_DIMENSION[1]/
2;S=CANVAS_WIDTH-102-e.x;T=102+e.x;Q=!1};this.deactiveSmallPad=function(){a.gotoAndPlay("StoN");a.on("animationend",function(){a.gotoAndStop("normal")});e.x=PADDLE_DIMENSION[1]/2;S=CANVAS_WIDTH-102-e.x;T=102+e.x;da=!1};this.deactiveFloor=function(){var a=s_oSpriteLibrary.getSprite("powerup_edge");createjs.Tween.get(W).to({y:CANVAS_HEIGHT+a.height/2},800,createjs.Ease.backIn).call(function(){!1===aa?(s_oStage.removeChild(W),W=null):createjs.Tween.get(W).to({y:940},800,createjs.Ease.backOut)});for(a=
0;a<f.length;a++)f[a].downFloor(!1);aa=!1};this.deactiveMagnetic=function(){for(var b=s_oSpriteLibrary.getSprite("normal_ball"),d=0;d<f.length;d++)f[d].changeSprite(b,"normal");s_oStage.removeChild(a);this.createPadding(a.x);this.launchUnmagneticBall();M=!1};this.deactiveShot=function(){qa=null;ha=!1;G&&(G.gotoAndPlay("go"),G.on("animationend",function(){!1===ha&&(s_oStage.removeChild(G),G=null)}));e.x=PADDLE_DIMENSION[1]/2;S=CANVAS_WIDTH-EDGE_OFFSET-e.x;T=EDGE_OFFSET+e.x};this.checkOtherActiveBonus=
function(){!1===O&&!0===aa&&!1===M&&!1===ha&&(v=!1)};this.bonusGesture=function(){for(var b=0;b<U;b++)if(k[b].update(),void 0!==k[b]&&k[b].getX()>a.x-e.x-k[b].getInfoData("offsetX")&&k[b].getX()<a.x+e.x+k[b].getInfoData("offsetX")&&k[b].getY()>a.y-e.y-k[b].getInfoData("offsetY")&&k[b].getY()<a.y+e.y+k[b].getInfoData("offsetY")){switch(k[b].getInfoData("Type")){case 0:this.bonusLargePad();break;case 1:this.bonusFireBall();break;case 2:this.bonusFloor();break;case 3:this.bonusMagnetic();break;case 4:this.bonusLife();
break;case 5:this.bonusMultiBall();break;case 6:this.bonusShot();break;case 7:this.bonusSlowBall();break;case 8:this.bonusFastBall();break;case 9:this.bonusSmallPad()}this.unloadBonus(b);break}};this.unloadBonus=function(a){k[a].unload();k.splice(a,1);0<U&&U--;for(a=0;a<U;a++)k[a].resetTheIndex(a)};this.unloadBall=function(a){f[a].unload();f.splice(a,1);for(a=0;a<f.length;a++)f[a].resetTheIndex(a)};this.unloadBullet=function(a){d[a].unload();d.splice(a,1);la--;for(a=0;a<d.length;a++)d[a].setIndex(a)};
this.randomBonus=function(a,b){Math.floor(100*Math.random())<SPAWN_BONUS_PROBABILITY[l-1]&&0<t&&this.generateABonus(a,b)};this.unloadLevel=function(){for(var b=0;b<f.length;b++)f[b].unload(),f[b]=null;for(b=0;b<k.length;b++)k[b].unload(),k[b]=null;if(void 0!==d)for(b=0;b<d.length;b++)d[b].unload(),d[b]=null;!0===Q?this.deactiveLargePad():!0===da&&this.deactiveSmallPad();!0===ha&&(K=0,s_oStage.removeChild(G),G=null);!0===aa&&(s_oStage.removeChild(W),W=null);!0===M&&(s_oStage.removeChild(a),this.createPadding(a.x));
v=O=M=aa=Q=ha=!1;for(b=0;b<n.length;b++)n[b].unload(),n[b]=null;U=0;f=d=k=y=A=r=x=z=q=n=null;n=[];q=[];z=[];x=[];r=[];A=[];y=[];k=[];d=[];f=[]};this.update=function(){if(!1===m){C+=s_iTimeElaps;var a=parseInt(C/za);C-=za*a;for(var b=0;b<a;b++)for(var d=0;d<Aa;d++)this.__updatePhysics()}};s_oGame=this;var za=16,Aa=10;BALL_SPEED=c.ball_speed/Aa;BRICKS_SCORE=c.bricks_score;BRICKS_RESISTANCE=c.bricks_resistance;BRICKS_DESTRUCTIBLE=c.bricks_destructible;BONUS_SPEED=c.bonus_speed/Aa;BONUS_TIME=c.bonus_time;
BONUS_SCORE=c.bonus_score;BULLET_SPEED=c.bullet_speed;LIFE=c.life;SPEED_DOWN_BALL=c.speed_down_ball;SPEED_UP_BALL=c.speed_up_ball;NUM_LEVELS_FOR_ADS=c.num_levels_for_ads;this._init(h)}var s_oGame;function CSettingsLevel(){this.createBonusOccurance=function(c){c=BONUS_OCCURRENCE_PER_LEVEL[c];for(var h=[],b=0;b<c.length;b++)for(var g=0;g<c[b];g++)h.push(b);return h};this.unload=function(){s_oAlienSettings=null};s_oAliensSettings=this}var s_oAliensSettings;
function CInterface(c){var h,b,g,l,m,f,n,d,a,e,p,w,C,y,A,r,x,q,z,H,P,N,J,t,R,L,B,D,ba,Z=null,S=null;this._init=function(c){var p=s_oSpriteLibrary.getSprite("icon_audio"),q=CANVAS_WIDTH-p.width/2-130;y=createBitmap(s_oSpriteLibrary.getSprite("up_edges"));s_oStage.addChild(y);!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(m=q,f=p.height/2+10,a=new CToggle(m,f,p,s_bAudioActive),a.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this),h=m-p.width/2-10,b=f):(h=q,b=p.height/2+10);q=window.document;p=q.documentElement;
Z=p.requestFullscreen||p.mozRequestFullScreen||p.webkitRequestFullScreen||p.msRequestFullscreen;S=q.exitFullscreen||q.mozCancelFullScreen||q.webkitExitFullscreen||q.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(Z=!1);Z&&screenfull.enabled&&(p=s_oSpriteLibrary.getSprite("but_fullscreen"),ba=new CToggle(h,b,p,s_bFullscreen,!0),ba.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));x=new createjs.Text(TEXT_SCORE+"\n"+c,"normal 40px "+PRIMARY_FONT,"#ffffff");x.textAlign="center";x.textBaseline=
"alphabetic";x.x=CANVAS_WIDTH/2-70;x.y=CANVAS_HEIGHT/2-400;s_oStage.addChild(x);D=new createjs.Text(TEXT_LEVEL_UPPERCASE,"normal 40px "+PRIMARY_FONT,"#ffffff");D.textAlign="center";D.textBaseline="alphabetic";D.x=CANVAS_WIDTH/2-240;D.y=CANVAS_HEIGHT/2-400;s_oStage.addChild(D);c=s_oSpriteLibrary.getSprite("but_exit");q=CANVAS_WIDTH-c.width/2-100;g=q+85;l=c.height/2+10;w=new CGfxButton(g,l,c,s_oStage);w.addEventListener(ON_MOUSE_UP,this._onExit,this);c=s_oSpriteLibrary.getSprite("but_pause");n=q=CANVAS_WIDTH-
c.width/2-90;d=c.height/2+10;e=new CGfxButton(n,d,c,s_oStage);e.addEventListener(ON_MOUSE_UP,this._onButPauseRelease,this);c=s_oSpriteLibrary.getSprite("life");A=createBitmap(c);A.x=.5*CANVAS_WIDTH+60;A.y=120;A.regX=.5*c.width;A.regY=.5*c.width;s_oStage.addChild(A);r=new createjs.Text("x"+LIFE,"normal 40px "+PRIMARY_FONT,"#ffffff");r.textAlign="center";r.textBaseline="alphabetic";r.x=.5*CANVAS_WIDTH+100;r.y=125;s_oStage.addChild(r);s_oGame.setPause(!0);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};
this.refreshButtonPos=function(c,p){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.setPosition(m-c,f+p);Z&&screenfull.enabled&&ba.setPosition(h-c,b+p);e.setPosition(n-c,d+p);w.setPosition(g-c,l+p)};this.rereshNumLevel=function(){};this.refreshBallLife=function(a){r.text="x"+ +a};this.gameOver=function(a){s_oGame.setPause(!0);e.block(!0);q=new createjs.Shape;q.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);q.alpha=0;s_oStage.addChild(q);H=new createjs.Text(TEXT_SCORE_GAMEOVER+"\n\n"+
a,"normal 90px "+PRIMARY_FONT,"#ffff00");H.textAlign="center";H.textBaseline="alphabetic";H.x=CANVAS_WIDTH/2;H.y=-120;s_oStage.addChild(H);createjs.Tween.get(q).to({alpha:.5},1E3,createjs.Ease.backOut).call(function(){createjs.Tween.get(H).to({y:CANVAS_HEIGHT/2-200},1E3,createjs.Ease.bounceOut).call(function(){var a=s_oSpriteLibrary.getSprite("but_restart");z=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/2+200,a,s_oStage);z.addEventListener(ON_MOUSE_UP,s_oInterface._onButReturnToMenuRelease,this)})});
$(s_oMain).trigger("share_event",a);$(s_oMain).trigger("save_score",a);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile){var b=playSound("game_over",1,!1);setVolume("soundtrack",.04);b.on("end",function(){setVolume("soundtrack",1);b=null})}};this.levelComplete=function(a,b){a<BRICKS_LEVEL_POSITION.length?(q=createBitmap(s_oSpriteLibrary.getSprite("msg_box")),q.alpha=0,s_oStage.addChild(q),s_oStage.setChildIndex(q,s_oStage.numChildren-1),e.block(!0),J=new createjs.Text(TEXT_LEVEL+" "+a+" "+TEXT_COMPLETE,
"normal 90px "+PRIMARY_FONT,"#ffff00"),J.textAlign="center",J.textBaseline="alphabetic",J.x=CANVAS_WIDTH/2,J.y=-140,s_oStage.addChild(J),t=new createjs.Text(TEXT_SCORE+"\n\n"+b,"normal 90px "+PRIMARY_FONT,"#ffff00"),t.textAlign="center",t.textBaseline="alphabetic",t.x=CANVAS_WIDTH/2,t.y=CANVAS_HEIGHT/2-40,t.alpha=0,s_oStage.addChild(t),createjs.Tween.get(q).to({alpha:1},1E3,createjs.Ease.backOut),createjs.Tween.get(t).to({alpha:1},1E3,createjs.Ease.bounceOut).call(function(){var a=s_oSpriteLibrary.getSprite("but_continue");
N=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/2+300,a,s_oStage);N.addEventListener(ON_MOUSE_UP,s_oInterface._onButNextLevelRelease,this)}),createjs.Tween.get(J).to({y:CANVAS_HEIGHT/2-300},1E3,createjs.Ease.bounceOut)):this.finishGame(b)};this.finishGame=function(a){s_oGame.setPause(!0);e.block(!0);q=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));q.alpha=0;s_oStage.addChild(q);s_oStage.setChildIndex(q,s_oStage.numChildren-1);R=new createjs.Text(TEXT_CONGRATULATIONS,"normal 70px "+PRIMARY_FONT,
"#ffff00");R.textAlign="center";R.textBaseline="alphabetic";R.lineWidth=500;R.lineHeight=60;R.x=CANVAS_WIDTH/2;R.y=-120;s_oStage.addChild(R);H=new createjs.Text(TEXT_SCORE_GAMEOVER+"\n\n"+a,"normal 80px "+PRIMARY_FONT,"#ffff00");H.textAlign="center";H.textBaseline="alphabetic";H.x=CANVAS_WIDTH/2;H.y=CANVAS_HEIGHT/2-50;H.alpha=0;s_oStage.addChild(H);createjs.Tween.get(q).to({alpha:1},1E3,createjs.Ease.backOut);createjs.Tween.get(R).to({y:CANVAS_HEIGHT/2-310},1200,createjs.Ease.bounceOut);createjs.Tween.get(H).to({alpha:1},
1E3,createjs.Ease.bounceOut).call(function(){var a=s_oSpriteLibrary.getSprite("but_restart");z=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/2+300,a,s_oStage);z.addEventListener(ON_MOUSE_UP,s_oInterface._onButReturnToMenuRelease,this)});if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile){var b=playSound("game_completed",1,!1);setVolume("soundtrack",.04);b.on("end",function(){setVolume("soundtrack",1);b=null})}$(s_oMain).trigger("save_score",a);$(s_oMain).trigger("share_event",a)};this._onButNextLevelRelease=
function(){s_oStage.removeChild(J,t,q);t=q=J=null;N.unload();N=null;e.block(!1);s_oGame.nextLevel()};this._onButReturnToMenuRelease=function(){s_oGame.onExit()};this.refreshScore=function(a){x.text="SCORE\n"+a};this._onButPauseRelease=function(){playSound("click",1,!1);s_oGame.setPause(!0);P=new createjs.Shape;P.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);P.alpha=.5;s_oStage.addChild(P);p=new createjs.Text("Pause","normal 70px "+PRIMARY_FONT,"#ffffff");p.textAlign="center";
p.textBaseline="alphabetic";p.x=CANVAS_WIDTH/2;p.y=CANVAS_HEIGHT/2-250;s_oStage.addChild(p);e.block(!0);w.block(!0);createjs.Ticker.paused=!0;var a=s_oSpriteLibrary.getSprite("but_continue");C=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/2,a,s_oStage);C.addEventListener(ON_MOUSE_UP,this._onButContinueRelease,this)};this._onButContinueRelease=function(){playSound("click",1,!1);C.unload();C=null;s_oStage.removeChild(p,P);P=!1;p=null;e.block(!1);w.block(!1);createjs.Ticker.paused=!1;s_oGame.setPause(!1)};
this.help=function(a){var b=s_oSpriteLibrary.getSprite("msg_box");L=createBitmap(b);L.on("click",function(){s_oInterface.unloadHelp(a)},null,!0);s_oStage.addChild(L);B?B.text=!0===s_bMobile?TEXT_HELP_PAGE_1_MOBILE:TEXT_HELP_PAGE_1_PC:(B=new createjs.Text(TEXT_HELP_PAGE_1_PC,"normal 60px "+PRIMARY_FONT,"#ffff00"),B.textAlign="center",B.textBaseline="alphabetic",B.lineWidth=500,B.lineHeight=50,B.x=CANVAS_WIDTH/2,B.y=CANVAS_HEIGHT/2-100,s_oStage.addChild(B))};this.unloadHelp=function(a){createjs.Tween.get(L).to({alpha:0},
1E3,createjs.Ease.cubicOut).call(function(){s_oStage.removeChild(L)});createjs.Tween.get(B).to({alpha:0},1E3,createjs.Ease.cubicOut).call(function(){s_oStage.removeChild(B);s_oInterface.showNumLevel(a)})};this.numLevel=function(a){D.text=TEXT_LEVEL_UPPERCASE+"\n"+a};this.showNumLevel=function(a){var b=new createjs.Text(TEXT_LEVEL_UPPERCASE+" "+a,"normal 100px "+PRIMARY_FONT,COLOR_TEXT_LEVEL[Math.floor(4*Math.random())]);b.textAlign="center";b.textBaseline="alphabetic";b.x=0;b.y=0;a=new createjs.Text(TEXT_LEVEL_UPPERCASE+
" "+a,"normal 100px "+PRIMARY_FONT,"#000000");a.textAlign="center";a.textBaseline="alphabetic";a.x=0;a.y=0;a.outline=5;var d=new createjs.Container;d.addChild(a,b);d.x=-100;d.y=.5*CANVAS_HEIGHT;s_oStage.addChild(d);createjs.Tween.get(d).to({x:.5*CANVAS_WIDTH},600,createjs.Ease.cubicOut).call(function(){createjs.Tween.get(d).wait(500).to({x:CANVAS_WIDTH+100},600,createjs.Ease.cubicIn).call(function(){s_oStage.removeChild(d);s_oGame.setPause(!1)})})};this.unload=function(){s_oStage.removeChild(H,z,
q);q=z=H=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)a.unload(),a=null;Z&&screenfull.enabled&&ba.unload();s_oInterface=null};this._onExit=function(){s_oGame.onExit()};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this.resetFullscreenBut=function(){Z&&screenfull.enabled&&ba.setActive(s_bFullscreen)};this._onFullscreenRelease=function(){s_bFullscreen?S.call(window.document):Z.call(window.document.documentElement);sizeHandler()};s_oInterface=this;this._init(c);
return this}var s_oInterface=null;
function CBall(c,h,b,g,l,m,f,n){var d,a={},e,p,w,C,y,A,r,x,q,z,H,P,N=0;this._init=function(){if(f){var a=new createjs.SpriteSheet({images:[b],frames:{width:b.width/8,height:b.height,regX:b.width/2/8,regY:b.height/2},animations:{fire:[0,7,"fire",.5]}});d=createSprite(a,"fire",b.width/2/8,b.height/2,b.width/8,b.height)}else d=createBitmap(b);d.x=c;d.y=h;w=n+OFFSET_RADIUS_BALL;z=!1;e=new CVector2(g,l);p=new CVector2(0,-1);d.regX=w;d.regY=w;a=OFFSETEDGELEFT+w;var t=-OFFSETEDGEDOWN-w,R=OFFSETEDGEUP+w;
C=CANVAS_WIDTH+(-OFFSETEDGERIGHT-w);y=a;r=CANVAS_HEIGHT+t-w;A=R+w;q=CANVAS_HEIGHT+w;x=CANVAS_HEIGHT+t-w+OFFSETPOWERUPFLOOR;P=m;H=BALL_SPEED*P;s_oStage.addChild(d);s_oStage.setChildIndex(d,1)};this.changeDirection=function(a,b,d,f){!0===d?e.set(a,e.getY()*b):"base"===f?e.set(e.getX()*a,b):"side"===f?e.set(e.getX()*a,e.getY()*b):"launch"===f&&e.set(a,b)};this.changeSprite=function(a,b){var e=d.x,f=d.y;if("fire"===b){s_oStage.removeChild(d);d=null;var c=new createjs.SpriteSheet({images:[a],frames:{width:a.width/
8,height:a.height,regX:a.width/2/8,regY:a.height/2},animations:{fire:[0,7,"fire",.5]}});d=createSprite(c,"fire",a.width/2/8,a.height/2,a.width/8,a.height);d.x=e;d.y=f}else s_oStage.removeChild(d),d=createBitmap(a),d.x=e,d.y=f,d.regX=w,d.regY=w;s_oStage.addChild(d);this.changeRotation();s_oStage.setChildIndex(d,1)};this.downFloor=function(a){z=a};this.getDirectionY=function(){return e.getY()};this.getX=function(){return d.x};this.getY=function(){return d.y};this.setDirection=function(a,b){e.normalize();
e.set(a,b);this.changeRotation()};this.changeRotation=function(){N=Math.round(toDegree(e.angleBetweenVectors(p)));0<e.getY()?(N*=-1,0<=e.getX()&&(N*=-1)):0>=e.getX()&&(N*=-1);d.rotation=N};this.setPosition=function(a,b){null!==a&&(d.x=a);null!==b&&(d.y=b)};this.setInfoData=function(b,d){a[b]=d};this.getInfoData=function(b){return a[b]};this.resetTheIndex=function(b){a.ID=b};this.unload=function(){s_oStage.removeChild(d);s_oBall=null};this.setVelocityRate=function(a){P=a;H=BALL_SPEED*P};this.update=
function(){d.x+=H*e.getX();d.y+=H*e.getY();d.x>=C?(e.set(-1*e.getX(),e.getY()),this.changeRotation(),--d.x,playSound("boing",1,!1)):d.x<=y?(e.set(-1*e.getX(),e.getY()),this.changeRotation(),d.x+=1,playSound("boing",1,!1)):d.y>=r&&!0===z&&d.y<x?(e.set(e.getX(),-1*e.getY()),this.changeRotation(),playSound("boing",1,!1)):d.y<=A?(e.set(e.getX(),-1*e.getY()),this.changeRotation(),playSound("boing",1,!1)):d.y>q?s_oGame.loseBall(a.ID):d.x<=y-1?d.x+=2:d.x>=C+1?d.x-=2:d.y<=A-1&&(d.y+=2)};s_oBall=this;this._init()}
var s_oBall;
function CBrick(c,h,b,g,l){var m,f={};this._init=function(){if(1>g&&!0===l)m=createBitmap(b),m.regX=b.width/2,m.regY=b.height/2,f.Effect=!1;else if(!0===l){var n={images:[b],frames:{width:b.width/4,height:b.height/2,regX:b.width/2/4,regY:b.height/2/2},animations:{normal:[1],destoyed:[2,7,"destroyed",.5]}};n=new createjs.SpriteSheet(n);m=createSprite(n,"normal",b.width/2/4,b.height/2/2,b.width/4,b.height/2);f.Effect=!0}else n={images:[b],frames:{width:b.width/8,height:b.height/2,regX:b.width/2/8,regY:b.height/
2/2},animations:{reflect:[0,15,"reflect",.5]}},n=new createjs.SpriteSheet(n),m=createSprite(n,0,b.width/2/8,b.height/2/2,b.width/8,b.height/2),f.Effect=!1,f.Reflect=!1;m.x=c;m.y=h;s_oStage.addChild(m)};this.getX=function(){return m.x};this.getY=function(){return m.y};this.setInfoData=function(b,d){f[b]=d};this.getInfoData=function(b){return f[b]};this.animBrick=function(b){m.gotoAndPlay(b);m.on("animationend",function(){s_oStage.removeChild(m)})};this.reflectBrick=function(){!0!==f.Reflect&&(m.gotoAndPlay("reflect"),
m.on("animationend",function(){m.gotoAndStop("reflect");f.Reflect=!1}))};this.setPosition=function(b,d){m.x=b;m.y=d};this.setChildIndex=function(b){s_oStage.setChildIndex(m,b)};this.damageBrick=function(b){m.gotoAndStop(b)};this.unload=function(){s_oStage.removeChild(m);s_oBrick=null};this.update=function(){};s_oBrick=this;this._init()}var s_oBrick;
function CBonus(c,h,b,g,l){var m,f={},n,d;this._init=function(a,b,c,g,h){f.Type=g;f.ID=h;0===g||7===g||9===g?(g={images:[c],frames:{width:c.width/5,height:c.height/2,regX:c.width/2/5,regY:c.height/2/2},animations:{normal:[0,9,"normal",1]}},g=new createjs.SpriteSheet(g),m=createSprite(g,"normal",c.width/2/5,c.height/2/2,c.width/5,c.height/2),f.offsetX=c.width/5/2):1===g||2===g||4===g||5===g||8===g?(g={images:[c],frames:{width:c.width/4,height:c.height/2,regX:c.width/2/4,regY:c.height/2/2},animations:{normal:[0,
7,"normal",1]}},g=new createjs.SpriteSheet(g),m=createSprite(g,"normal",c.width/2/4,c.height/2/2,c.width/4,c.height/2),f.offsetX=c.width/4/2):(g={images:[c],frames:{width:c.width/6,height:c.height/2,regX:c.width/2/6,regY:c.height/2/2},animations:{normal:[0,11,"normal",1]}},g=new createjs.SpriteSheet(g),m=createSprite(g,"normal",c.width/2/6,c.height/2/2,c.width/6,c.height/2),f.offsetX=c.width/6/2);f.offsetY=c.height/2/2;n=BONUS_SPEED;m.x=a;m.y=b;s_oStage.addChild(m);d=CANVAS_HEIGHT+f.offsetX};this.getX=
function(){return m.x};this.getY=function(){return m.y};this.setInfoData=function(a,b){f[a]=b};this.getInfoData=function(a){return f[a]};this.resetTheIndex=function(a){f.ID=a};this.unload=function(){s_oStage.removeChild(m)};this.update=function(){m.y+=n;m.y<d||s_oGame.unloadBonus(f.ID)};s_oBonus=this;this._init(c,h,b,g,l)}var s_oBonus;
function CBullet(c,h,b){var g,l,m;this._init=function(){var f=b.height/2;g=createBitmap(b);g.x=c;g.y=h;g.regX=b.width/2;g.regY=f;s_oStage.addChild(g);l=30+f+f};this.getX=function(){return g.x};this.getY=function(){return g.y};this.setPosition=function(b,c){null!==b&&(g.x=b);null!==c&&(g.y=c)};this.unload=function(){s_oStage.removeChild(g);s_oBullet=null};this.setIndex=function(b){m=b};this.getIndex=function(){return m};this.update=function(){g.y-=BULLET_SPEED;g.y<l&&(s_oGame.unloadBullet(m),playSound("brick_metal",
1,!1))};s_oBullet=this;this._init()}var s_oBullet;
function CVector2(c,h){var b,g;this._init=function(c,h){b=c;g=h};this.add=function(c,h){b+=c;g+=h};this.addV=function(c){b+=c.getX();g+=c.getY()};this.scalarDivision=function(c){b/=c;g/=c};this.subV=function(c){b-=c.getX();g-=c.getY()};this.scalarProduct=function(c){b*=c;g*=c};this.invert=function(){b*=-1;g*=-1};this.dotProduct=function(c){return b*c.getX()+g*c.getY()};this.set=function(c,h){b=c;g=h};this.setV=function(c){b=c.getX();g=c.getY()};this.length=function(){return Math.sqrt(b*b+g*g)};this.length2=
function(){return b*b+g*g};this.normalize=function(){var c=this.length();0<c&&(b/=c,g/=c)};this.angleBetweenVectors=function(b){b=Math.acos(this.dotProduct(b)/(this.length()*b.length()));return!0===isNaN(b)?0:b};this.getNormalize=function(c){this.length();c.set(b,g);c.normalize()};this.rot90CCW=function(){var c=b;b=-g;g=c};this.rot90CW=function(){var c=b;b=g;g=-c};this.getRotCCW=function(c){c.set(b,g);c.rot90CCW()};this.getRotCW=function(c){c.set(b,g);c.rot90CW()};this.ceil=function(){b=Math.ceil(b);
g=Math.ceil(g)};this.round=function(){b=Math.round(b);g=Math.round(g)};this.toString=function(){return"Vector2: "+b+", "+g};this.print=function(){trace("Vector2: "+b+", "+g)};this.getX=function(){return b};this.getY=function(){return g};this._init(c,h)}
function CLevelMenu(c){var h,b,g,l,m,f=[],n,d,a,e;this._init=function(){n=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));n.x=0;n.y=0;s_oStage.addChild(n);n=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));s_oStage.addChild(n);m=new createjs.Text(TEXT_LEVEL_UPPERCASE," 50px "+PRIMARY_FONT,"#ffffff");m.x=CANVAS_WIDTH/2;m.y=400;m.textAlign="center";m.textBaseline="alphabetic";m.lineWidth=1E3;s_oStage.addChild(m);for(var c=.5*CANVAS_WIDTH-20,w=0,C=50,y=0;y<BRICKS_LEVEL_POSITION.length;y++,w+=
110)440<w&&(w=0,C+=100),y<s_iLastLevel?(f[y]=new CLevelBut(c-200+w,425+C,s_oSpriteLibrary.getSprite("but_level"),!0,y+1),f[y].addEventListenerWithParams(ON_MOUSE_DOWN,this._onClick,this,y)):f[y]=new CLevelBut(c-200+w,425+C,s_oSpriteLibrary.getSprite("but_level"),!1,y+1),s_bFirstTime=!0;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)w=s_oSpriteLibrary.getSprite("icon_audio"),h=c=CANVAS_WIDTH-w.width/2-60,b=w.height/2+10,a=new CToggle(h,b,w,s_bAudioActive),a.addEventListener(ON_MOUSE_UP,this._onAudioToggle,
this);w=s_oSpriteLibrary.getSprite("but_exit");c=CANVAS_WIDTH-w.width/2-100;g=c+85;l=w.height/2+10;d=new CGfxButton(g,l,w,s_oStage);d.addEventListener(ON_MOUSE_UP,this._onExit,this);e=new createjs.Shape;e.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(e);createjs.Tween.get(e).to({alpha:0},1E3).call(function(){s_oStage.removeChild(e)});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){for(var a=0;a<BRICKS_LEVEL_POSITION.length;a++)f[a].unload();
s_oLevelMenu=null;s_oStage.removeAllChildren()};this.refreshButtonPos=function(c,e){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.setPosition(h-c,b+e);d.setPosition(g-c,l+e)};this._onNumModeToggle=function(a){a===NUM_ACTIVE?((void 0).setActive(!1),(void 0).setActive(!0)):((void 0).setActive(!0),(void 0).setActive(!1))};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onClick=function(a){f[a].ifClickable()&&($(s_oMain).trigger("start_session"),s_oMain.levelSelected(a+
1))};this._onExit=function(){s_oLevelMenu.unload();s_oMain.gotoMenu()};s_oLevelMenu=this;this._init()}var s_oLevelMenu=null;
function CLevelBut(c,h,b,g,l){var m,f,n,d=[],a=[],e;this._init=function(a,b,c,g){f=[];n=[];var h=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});m=g;e=createSprite(h,"state_"+m,c.width/2/2,c.height/2,c.width/2,c.height);e.mouseEnabled=g;e.x=a;e.y=b;e.stop();s_bMobile||(e.cursor="pointer");s_oStage.addChild(e);d.push(e);c=new createjs.Text(l,"50px "+PRIMARY_FONT,"#ffff00");c.x=a;c.y=b+15;c.textAlign=
"center";c.textBaseline="alphabetic";c.lineWidth=200;s_oStage.addChild(c);this._initListener()};this.unload=function(){e.off("mousedown",this.buttonDown);e.off("pressup",this.buttonRelease);s_oStage.removeChild(e)};this._initListener=function(){e.on("mousedown",this.buttonDown);e.on("pressup",this.buttonRelease)};this.viewBut=function(a){s_oStage.addChild(a)};this.addEventListener=function(a,b,c){f[a]=b;n[a]=c};this.addEventListenerWithParams=function(b,c,d,e){f[b]=c;n[b]=d;a=e};this.ifClickable=
function(){return!0===e.mouseEnabled?1:0};this.setActive=function(a,b){m=b;d[a].gotoAndStop("state_"+m);d[a].mouseEnabled=!0};this.buttonRelease=function(){e.scaleX=1;e.scaleY=1;playSound("click",1,!1);m=!m;e.gotoAndStop("state_"+m);f[ON_MOUSE_UP]&&f[ON_MOUSE_UP].call(n[ON_MOUSE_UP],a)};this.buttonDown=function(){e.scaleX=.9;e.scaleY=.9;f[ON_MOUSE_DOWN]&&f[ON_MOUSE_DOWN].call(n[ON_MOUSE_DOWN],a)};this.setPosition=function(a,b){e.x=a;e.y=b};this.setVisible=function(a){e.visible=a};this._init(c,h,b,
g)}
function CCreditsPanel(){var c,h,b,g,l,m,f,n;this._init=function(){n=new createjs.Container;s_oStage.addChild(n);var d=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));n.addChild(d);l=new createjs.Shape;l.graphics.beginFill("rgba(0,0,0,0.7)").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);n.addChild(l);d=s_oSpriteLibrary.getSprite("msg_box");h=createBitmap(d);h.x=CANVAS_WIDTH/2;h.y=CANVAS_HEIGHT/2;h.regX=d.width/2;h.regY=d.height/2;n.addChild(h);m=new createjs.Shape;m.graphics.beginFill("#0f0f0f").drawRect(0,0,
CANVAS_WIDTH,CANVAS_HEIGHT);m.alpha=.01;m.on("click",this._onLogoButRelease);n.addChild(m);d=s_oSpriteLibrary.getSprite("but_exit");c=CANVAS_WIDTH/2+264;b=new CGfxButton(c,394,d,n);b.addEventListener(ON_MOUSE_UP,this.unload,this);g=new createjs.Text(TEXT_DEVELOPED,"46px "+PRIMARY_FONT,"#ffffff");g.x=CANVAS_WIDTH/2;g.y=420;g.textAlign="center";n.addChild(g);d=s_oSpriteLibrary.getSprite("ctl_logo");var a=createBitmap(d);a.regX=d.width/2;a.regY=d.height/2;a.x=CANVAS_WIDTH/2;a.y=CANVAS_HEIGHT/2;n.addChild(a);
f=new createjs.Text("www.codethislab.com","46px "+PRIMARY_FONT,"#ffffff");f.x=CANVAS_WIDTH/2;f.y=570;f.textAlign="center";n.addChild(f)};this.unload=function(){m.off("click",this._onLogoButRelease);b.unload();b=null;s_oStage.removeChild(n)};this._onLogoButRelease=function(){window.open("http://www.codethislab.com/index.php?&l=en")};this._init()}
function CAlertSavingBox(c,h){var b,g,l;this._init=function(c){l=new createjs.Container;f.addChild(l);var d=new createjs.Shape;d.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);d.alpha=.5;d.on("click",function(){});l.addChild(d);d=s_oSpriteLibrary.getSprite("msg_box");var a=createBitmap(d);a.x=.5*CANVAS_WIDTH;a.y=.5*CANVAS_HEIGHT;a.regX=.5*d.width;a.regY=.5*d.height;l.addChild(a);b=new createjs.Text(c,"28px "+PRIMARY_FONT,"#fff");b.x=CANVAS_WIDTH/2;b.y=350;b.textAlign="center";
b.textBaseline="middle";b.lineWidth=d.width-50;l.addChild(b);g=new CSideGfxButton(!1,944,250,s_oSpriteLibrary.getSprite("but_exit"),l);g.addEventListener(ON_MOUSE_UP,this._onButOk,this)};this._onButOk=function(){m.unload()};this.unload=function(){g.unload();f.removeChild(l)};var m=this;var f=h;this._init(c)}
function CAreYouSurePanel(){var c,h,b,g,l,m,f,n,d=this;this._init=function(){c=[];h=[];f=new createjs.Container;f.visible=!1;s_oStage.addChild(f);n=new createjs.Shape;n.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);n.alpha=.5;n.on("click",function(){});f.addChild(n);var a=s_oSpriteLibrary.getSprite("msg_box");b=createBitmap(a);b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT/2;b.regX=.5*a.width;b.regY=.5*a.height;f.addChild(b);g=new createjs.Text(TEXT_ARE_SURE,"44px "+PRIMARY_FONT,"#ffffff");
g.x=CANVAS_WIDTH/2;g.y=CANVAS_HEIGHT/2-90;g.textAlign="center";g.textBaseline="middle";g.lineWidth=a.width-300;g.lineHeight=40;f.addChild(g);l=new CGfxButton(CANVAS_WIDTH/2+150,.5*CANVAS_HEIGHT+70,s_oSpriteLibrary.getSprite("but_yes"),f);l.addEventListener(ON_MOUSE_UP,this._onButYes,this);m=new CGfxButton(CANVAS_WIDTH/2-150,.5*CANVAS_HEIGHT+70,s_oSpriteLibrary.getSprite("but_no"),f);m.addEventListener(ON_MOUSE_UP,this._onButNo,this)};this.addEventListener=function(a,b,d){c[a]=b;h[a]=d};this.show=
function(a){g.text=a;f.alpha=0;f.visible=!0;createjs.Tween.get(f).to({alpha:1},300,createjs.Ease.quartOut).call(function(){s_oMain.stopUpdateNoBlock()})};this.hide=function(){s_oMain.startUpdateNoBlock();createjs.Tween.get(f).to({alpha:0},500,createjs.Ease.quartOut).call(function(){f.visible=!1})};this.unload=function(){m.unload();l.unload()};this._onButYes=function(){d.hide();c[ON_BUT_YES_DOWN]&&c[ON_BUT_YES_DOWN].call(h[ON_BUT_YES_DOWN])};this._onButNo=function(){d.hide()};this._init()};